"""baseline_inicial

Revision ID: 99586a8d3d96
Revises:
Create Date: 2026-03-09 06:44:39.044448

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "99586a8d3d96"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "empresas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome_fantasia", sa.String(length=200), nullable=False),
        sa.Column("cnpj", sa.String(length=18), nullable=False),
        sa.Column("plano_ativo", sa.String(length=20), nullable=False),
        sa.Column("custo_gerado_reais", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("mensagens_processadas", sa.Integer(), nullable=False),
        sa.Column("status_bloqueio", sa.Boolean(), nullable=False),
        sa.Column("bloqueado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("motivo_bloqueio", sa.String(length=300), nullable=True),
        sa.Column("segmento", sa.String(length=100), nullable=True),
        sa.Column("cidade_estado", sa.String(length=100), nullable=True),
        sa.Column("nome_responsavel", sa.String(length=150), nullable=True),
        sa.Column("observacoes", sa.Text(), nullable=True),
        sa.Column("criado_em", sa.DateTime(timezone=True), nullable=False, comment="Timestamp UTC de criação"),
        sa.Column("atualizado_em", sa.DateTime(timezone=True), nullable=True, comment="Timestamp UTC da última atualização"),
        sa.CheckConstraint("LENGTH(REPLACE(REPLACE(REPLACE(cnpj, '.', ''), '/', ''), '-', '')) = 14", name="ck_empresa_cnpj_tamanho"),
        sa.CheckConstraint("plano_ativo IN ('Inicial', 'Intermediario', 'Ilimitado')", name="ck_empresa_plano_valido"),
        sa.CheckConstraint("custo_gerado_reais >= 0", name="ck_empresa_custo_nao_negativo"),
        sa.CheckConstraint("mensagens_processadas >= 0", name="ck_empresa_msgs_nao_negativo"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("empresas", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_empresas_cnpj"), ["cnpj"], unique=True)
        batch_op.create_index(batch_op.f("ix_empresas_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_empresas_nome_fantasia"), ["nome_fantasia"], unique=False)

    op.create_table(
        "limites_plano",
        sa.Column("plano", sa.String(length=20), nullable=False),
        sa.Column("laudos_mes", sa.Integer(), nullable=True),
        sa.Column("usuarios_max", sa.Integer(), nullable=True),
        sa.Column("upload_doc", sa.Boolean(), nullable=False),
        sa.Column("deep_research", sa.Boolean(), nullable=False),
        sa.Column("integracoes_max", sa.Integer(), nullable=True),
        sa.Column("retencao_dias", sa.Integer(), nullable=True),
        sa.CheckConstraint("plano IN ('Inicial', 'Intermediario', 'Ilimitado')", name="ck_limite_plano_valido"),
        sa.CheckConstraint("integracoes_max IS NULL OR integracoes_max >= 0", name="ck_limite_integracoes_max_nao_negativo"),
        sa.CheckConstraint("laudos_mes IS NULL OR laudos_mes >= 0", name="ck_limite_laudos_mes_nao_negativo"),
        sa.CheckConstraint("retencao_dias IS NULL OR retencao_dias >= 0", name="ck_limite_retencao_dias_nao_negativo"),
        sa.CheckConstraint("usuarios_max IS NULL OR usuarios_max >= 0", name="ck_limite_usuarios_max_nao_negativo"),
        sa.PrimaryKeyConstraint("plano"),
    )
    op.create_table(
        "usuarios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("nome_completo", sa.String(length=150), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("crea", sa.String(length=40), nullable=True),
        sa.Column("senha_hash", sa.String(length=256), nullable=False),
        sa.Column("nivel_acesso", sa.Integer(), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("tentativas_login", sa.Integer(), nullable=False),
        sa.Column("bloqueado_ate", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ultimo_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ultimo_login_ip", sa.String(length=45), nullable=True),
        sa.Column("status_bloqueio", sa.Boolean(), nullable=False),
        sa.Column("senha_temporaria_ativa", sa.Boolean(), nullable=False),
        sa.Column("criado_em", sa.DateTime(timezone=True), nullable=False, comment="Timestamp UTC de criação"),
        sa.Column("atualizado_em", sa.DateTime(timezone=True), nullable=True, comment="Timestamp UTC da última atualização"),
        sa.CheckConstraint("nivel_acesso IN (1, 50, 99)", name="ck_usuario_nivel_acesso_valido"),
        sa.CheckConstraint("tentativas_login >= 0", name="ck_usuario_tentativas_nao_negativo"),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("usuarios", schema=None) as batch_op:
        batch_op.create_index("ix_usuario_empresa_email", ["empresa_id", "email"], unique=False)
        batch_op.create_index(batch_op.f("ix_usuarios_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_usuarios_empresa_id"), ["empresa_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_usuarios_id"), ["id"], unique=False)

    op.create_table(
        "laudos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=True),
        sa.Column("setor_industrial", sa.String(length=100), nullable=False),
        sa.Column("tipo_template", sa.String(length=50), nullable=False),
        sa.Column(
            "status_conformidade", sa.Enum("Pendente", "Conforme", "Nao Conforme", "Em Andamento", name="statuslaudo", native_enum=False), nullable=False
        ),
        sa.Column("status_revisao", sa.Enum("Rascunho", "Aguardando Aval", "Aprovado", "Rejeitado", name="statusrevisao", native_enum=False), nullable=False),
        sa.Column("revisado_por", sa.Integer(), nullable=True),
        sa.Column("motivo_rejeicao", sa.Text(), nullable=True),
        sa.Column("dados_formulario", sa.JSON(), nullable=True),
        sa.Column("parecer_ia", sa.Text(), nullable=True),
        sa.Column("confianca_ia_json", sa.JSON(), nullable=True),
        sa.Column("codigo_hash", sa.String(length=32), nullable=False),
        sa.Column("custo_api_reais", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("nome_arquivo_pdf", sa.String(length=100), nullable=True),
        sa.Column("primeira_mensagem", sa.String(length=80), nullable=True),
        sa.Column("pinado", sa.Boolean(), nullable=False),
        sa.Column("pinado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modo_resposta", sa.Enum("curto", "detalhado", "deep_research", name="modoresposta", native_enum=False), nullable=False),
        sa.Column("is_deep_research", sa.Boolean(), nullable=False),
        sa.Column("criado_em", sa.DateTime(timezone=True), nullable=False, comment="Timestamp UTC de criação"),
        sa.Column("atualizado_em", sa.DateTime(timezone=True), nullable=True, comment="Timestamp UTC da última atualização"),
        sa.CheckConstraint("custo_api_reais >= 0", name="ck_laudo_custo_nao_negativo"),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["revisado_por"], ["usuarios.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuarios.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("laudos", schema=None) as batch_op:
        batch_op.create_index("ix_laudo_empresa_criado", ["empresa_id", "criado_em"], unique=False)
        batch_op.create_index("ix_laudo_empresa_deep", ["empresa_id", "is_deep_research"], unique=False)
        batch_op.create_index("ix_laudo_empresa_pinado", ["empresa_id", "pinado"], unique=False)
        batch_op.create_index("ix_laudo_usuario_id", ["usuario_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_laudos_codigo_hash"), ["codigo_hash"], unique=True)
        batch_op.create_index(batch_op.f("ix_laudos_empresa_id"), ["empresa_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_laudos_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_laudos_usuario_id"), ["usuario_id"], unique=False)

    op.create_table(
        "sessoes_ativas",
        sa.Column("token", sa.String(length=180), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("criada_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expira_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ultima_atividade_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lembrar", sa.Boolean(), nullable=False),
        sa.Column("ip_hash", sa.String(length=64), nullable=True),
        sa.Column("user_agent_hash", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuarios.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token"),
    )
    with op.batch_alter_table("sessoes_ativas", schema=None) as batch_op:
        batch_op.create_index("ix_sessao_expira", ["expira_em"], unique=False)
        batch_op.create_index("ix_sessao_usuario_criada", ["usuario_id", "criada_em"], unique=False)
        batch_op.create_index(batch_op.f("ix_sessoes_ativas_usuario_id"), ["usuario_id"], unique=False)

    op.create_table(
        "citacoes_laudo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("laudo_id", sa.Integer(), nullable=False),
        sa.Column("referencia", sa.String(length=300), nullable=False),
        sa.Column("trecho", sa.Text(), nullable=True),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("ordem", sa.Integer(), nullable=False),
        sa.Column("criado_em", sa.DateTime(timezone=True), nullable=False, comment="Timestamp UTC de criação"),
        sa.Column("atualizado_em", sa.DateTime(timezone=True), nullable=True, comment="Timestamp UTC da última atualização"),
        sa.CheckConstraint("ordem >= 0", name="ck_citacao_ordem_nao_negativo"),
        sa.ForeignKeyConstraint(["laudo_id"], ["laudos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("citacoes_laudo", schema=None) as batch_op:
        batch_op.create_index("ix_citacao_laudo_id", ["laudo_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_citacoes_laudo_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_citacoes_laudo_laudo_id"), ["laudo_id"], unique=False)

    op.create_table(
        "laudo_revisoes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("laudo_id", sa.Integer(), nullable=False),
        sa.Column("numero_versao", sa.Integer(), nullable=False),
        sa.Column("origem", sa.String(length=20), nullable=False),
        sa.Column("resumo", sa.String(length=240), nullable=True),
        sa.Column("conteudo", sa.Text(), nullable=False),
        sa.Column("confianca_geral", sa.String(length=16), nullable=True),
        sa.Column("confianca_json", sa.JSON(), nullable=True),
        sa.Column("criado_em", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("numero_versao >= 1", name="ck_laudo_revisao_numero_positivo"),
        sa.ForeignKeyConstraint(["laudo_id"], ["laudos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("laudo_id", "numero_versao", name="uq_laudo_revisao_laudo_versao"),
    )
    with op.batch_alter_table("laudo_revisoes", schema=None) as batch_op:
        batch_op.create_index("ix_laudo_revisao_criado", ["laudo_id", "criado_em"], unique=False)
        batch_op.create_index("ix_laudo_revisao_laudo_versao", ["laudo_id", "numero_versao"], unique=False)
        batch_op.create_index(batch_op.f("ix_laudo_revisoes_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_laudo_revisoes_laudo_id"), ["laudo_id"], unique=False)

    op.create_table(
        "mensagens_laudo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("laudo_id", sa.Integer(), nullable=False),
        sa.Column("remetente_id", sa.Integer(), nullable=True),
        sa.Column("tipo", sa.String(length=20), nullable=False),
        sa.Column("conteudo", sa.Text(), nullable=False),
        sa.Column("lida", sa.Boolean(), nullable=False),
        sa.Column("resolvida_por_id", sa.Integer(), nullable=True),
        sa.Column("resolvida_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("custo_api_reais", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("criado_em", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("tipo IN ('user', 'ia', 'humano_insp', 'humano_eng')", name="ck_mensagem_tipo_valido"),
        sa.CheckConstraint("custo_api_reais >= 0", name="ck_mensagem_custo_nao_negativo"),
        sa.ForeignKeyConstraint(["laudo_id"], ["laudos.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["remetente_id"], ["usuarios.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["resolvida_por_id"], ["usuarios.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("mensagens_laudo", schema=None) as batch_op:
        batch_op.create_index("ix_mensagem_laudo_criado", ["laudo_id", "criado_em"], unique=False)
        batch_op.create_index("ix_mensagem_remetente", ["remetente_id"], unique=False)
        batch_op.create_index("ix_mensagem_resolvida_por", ["resolvida_por_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_mensagens_laudo_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_mensagens_laudo_laudo_id"), ["laudo_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("mensagens_laudo", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mensagens_laudo_laudo_id"))
        batch_op.drop_index(batch_op.f("ix_mensagens_laudo_id"))
        batch_op.drop_index("ix_mensagem_resolvida_por")
        batch_op.drop_index("ix_mensagem_remetente")
        batch_op.drop_index("ix_mensagem_laudo_criado")

    op.drop_table("mensagens_laudo")
    with op.batch_alter_table("laudo_revisoes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_laudo_revisoes_laudo_id"))
        batch_op.drop_index(batch_op.f("ix_laudo_revisoes_id"))
        batch_op.drop_index("ix_laudo_revisao_laudo_versao")
        batch_op.drop_index("ix_laudo_revisao_criado")

    op.drop_table("laudo_revisoes")
    with op.batch_alter_table("citacoes_laudo", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_citacoes_laudo_laudo_id"))
        batch_op.drop_index(batch_op.f("ix_citacoes_laudo_id"))
        batch_op.drop_index("ix_citacao_laudo_id")

    op.drop_table("citacoes_laudo")
    with op.batch_alter_table("sessoes_ativas", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessoes_ativas_usuario_id"))
        batch_op.drop_index("ix_sessao_usuario_criada")
        batch_op.drop_index("ix_sessao_expira")

    op.drop_table("sessoes_ativas")
    with op.batch_alter_table("laudos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_laudos_usuario_id"))
        batch_op.drop_index(batch_op.f("ix_laudos_id"))
        batch_op.drop_index(batch_op.f("ix_laudos_empresa_id"))
        batch_op.drop_index(batch_op.f("ix_laudos_codigo_hash"))
        batch_op.drop_index("ix_laudo_usuario_id")
        batch_op.drop_index("ix_laudo_empresa_pinado")
        batch_op.drop_index("ix_laudo_empresa_deep")
        batch_op.drop_index("ix_laudo_empresa_criado")

    op.drop_table("laudos")
    with op.batch_alter_table("usuarios", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_usuarios_id"))
        batch_op.drop_index(batch_op.f("ix_usuarios_empresa_id"))
        batch_op.drop_index(batch_op.f("ix_usuarios_email"))
        batch_op.drop_index("ix_usuario_empresa_email")

    op.drop_table("usuarios")
    op.drop_table("limites_plano")
    with op.batch_alter_table("empresas", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_empresas_nome_fantasia"))
        batch_op.drop_index(batch_op.f("ix_empresas_id"))
        batch_op.drop_index(batch_op.f("ix_empresas_cnpj"))

    op.drop_table("empresas")
    # ### end Alembic commands ###
