import { StyleSheet } from "react-native";

import { colors, radii, shadows, spacing } from "../../theme/tokens";
import {
  PANEL_EDGE_GESTURE_TOP_OFFSET,
  PANEL_EDGE_GESTURE_WIDTH,
  SIDE_PANEL_WIDTH,
} from "../InspectorMobileApp.constants";

export const chatModalStyles = {
  attachmentModalBackdrop: {
    flex: 1,
    backgroundColor: colors.overlayOpaque,
    padding: spacing.lg,
    justifyContent: "center",
  },
  activityModalBackdrop: {
    flex: 1,
    backgroundColor: colors.overlayStrong,
    padding: spacing.md,
    justifyContent: "flex-end",
  },
  appLockBackdrop: {
    flex: 1,
    backgroundColor: "rgba(6, 12, 20, 0.72)",
    padding: spacing.lg,
    alignItems: "center",
    justifyContent: "center",
  },
  appLockCard: {
    width: "100%",
    maxWidth: 420,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#2A3B4D",
    backgroundColor: "#0F1A26",
    padding: spacing.lg,
    gap: spacing.sm,
  },
  appLockIconShell: {
    width: 48,
    height: 48,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1D2B3A",
    borderWidth: 1,
    borderColor: "#2E435A",
  },
  appLockTitle: {
    color: "#F1F5F9",
    fontSize: 22,
    fontWeight: "800",
  },
  appLockText: {
    color: "#C9D6E3",
    fontSize: 13,
    lineHeight: 20,
  },
  appLockHint: {
    color: "#9BB0C5",
    fontSize: 12,
    lineHeight: 18,
  },
  appLockPrimaryButton: {
    minHeight: 46,
    borderRadius: 16,
    backgroundColor: colors.accent,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
    marginTop: spacing.xs,
  },
  appLockPrimaryButtonText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: "800",
  },
  appLockGhostButton: {
    minHeight: 44,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#2E435A",
    backgroundColor: "#152436",
    alignItems: "center",
    justifyContent: "center",
  },
  appLockGhostButtonText: {
    color: "#D0DEEC",
    fontSize: 13,
    fontWeight: "700",
  },
  activityModalCard: {
    backgroundColor: colors.surfacePanel,
    borderRadius: radii.xl,
    padding: spacing.lg,
    gap: spacing.md,
    maxHeight: "78%",
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    ...shadows.floating,
  },
  activityModalHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  activityModalCopy: {
    flex: 1,
    gap: 2,
  },
  activityModalEyebrow: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.9,
  },
  activityModalEyebrowPrint: {
    color: colors.textMuted,
  },
  activityModalEyebrowPrintDark: {
    color: "#C7D2DF",
  },
  settingsDrawerWordmark: {
    fontSize: 10,
    fontWeight: "600",
    letterSpacing: 1.1,
    opacity: 0.56,
  },
  settingsDrawerWordmarkPrint: {
    color: colors.ink600,
    opacity: 0.48,
  },
  settingsDrawerWordmarkPrintDark: {
    color: "#AFC0D2",
    opacity: 0.44,
  },
  activityModalTitle: {
    color: colors.textPrimary,
    fontSize: 22,
    fontWeight: "800",
  },
  activityModalDescription: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 18,
  },
  activityModalClose: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceCanvas,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
  },
  activityModalLoading: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  activityModalLoadingText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "600",
  },
  activityModalList: {
    gap: spacing.sm,
    paddingBottom: spacing.lg,
  },
  activityItem: {
    borderRadius: radii.md,
    backgroundColor: colors.surfacePanelRaised,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    padding: spacing.md,
    flexDirection: "row",
    gap: spacing.sm,
    ...shadows.soft,
  },
  activityItemUnread: {
    borderColor: colors.accentMuted,
    backgroundColor: colors.accentWash,
  },
  activityItemIcon: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    backgroundColor: "rgba(244,123,32,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  activityItemBody: {
    flex: 1,
    gap: 4,
  },
  activityItemTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  activityItemTitle: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "800",
  },
  activityItemTime: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "700",
  },
  activityItemText: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  activityItemHint: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "700",
  },
  activityEmptyState: {
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    paddingVertical: spacing.xxl,
  },
  activityEmptyTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "800",
  },
  activityEmptyText: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    textAlign: "center",
  },
  sidePanelLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 18,
  },
  sidePanelModalRoot: {
    flex: 1,
  },
  sidePanelEdgeHitbox: {
    position: "absolute",
    top: PANEL_EDGE_GESTURE_TOP_OFFSET,
    bottom: 0,
    width: PANEL_EDGE_GESTURE_WIDTH,
    zIndex: 2,
  },
  sidePanelEdgeHitboxLeft: {
    left: 0,
  },
  sidePanelEdgeHitboxRight: {
    right: 0,
  },
  sidePanelScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.overlaySoft,
    zIndex: 3,
  },
  sidePanelScrimPressable: {
    flex: 1,
  },
  sidePanelDrawer: {
    position: "absolute",
    top: spacing.sm,
    bottom: spacing.sm,
    width: SIDE_PANEL_WIDTH,
    backgroundColor: colors.surfacePanel,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.md,
    ...shadows.floating,
    zIndex: 4,
  },
  sidePanelDrawerPrint: {
    backgroundColor: colors.surfaceCanvas,
    borderColor: colors.surfaceStrokeStrong,
  },
  sidePanelDrawerPrintDark: {
    backgroundColor: "#131E2A",
    borderColor: "#2A3A4E",
  },
  sidePanelDrawerLeft: {
    left: spacing.md,
  },
  sidePanelDrawerRight: {
    right: spacing.md,
  },
  sidePanelHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
    marginBottom: spacing.md,
  },
  sidePanelCopy: {
    flex: 1,
    gap: 4,
  },
  sidePanelTitle: {
    color: colors.textPrimary,
    fontSize: 22,
    fontWeight: "800",
  },
  sidePanelTitlePrint: {
    color: colors.textPrimary,
  },
  sidePanelTitlePrintDark: {
    color: "#F0F4F8",
  },
  sidePanelDescription: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 17,
  },
  sidePanelDescriptionPrint: {
    color: colors.textSecondary,
  },
  sidePanelDescriptionPrintDark: {
    color: "#AFC0D2",
  },
  sidePanelCloseButton: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceCanvas,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  sidePanelCloseButtonPrint: {
    backgroundColor: colors.surfaceCanvas,
    borderColor: colors.surfaceStrokeStrong,
  },
  sidePanelCloseButtonPrintDark: {
    backgroundColor: "#1D2B3A",
    borderColor: "#32455D",
  },
  sidePanelActionList: {
    gap: spacing.sm,
    paddingBottom: spacing.xl,
  },
  attachmentModalCard: {
    backgroundColor: "#08111C",
    borderRadius: radii.lg,
    padding: spacing.md,
    gap: spacing.md,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  attachmentModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  attachmentModalTitle: {
    flex: 1,
    color: colors.white,
    fontSize: 14,
    fontWeight: "700",
  },
  attachmentModalClose: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  attachmentModalImage: {
    width: "100%",
    minHeight: 280,
    maxHeight: 520,
    borderRadius: radii.md,
    backgroundColor: "#03070D",
  },
  composerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.surfaceCanvas,
    borderRadius: 24,
    paddingLeft: 8,
    paddingRight: 8,
    paddingVertical: 5,
  },
  attachInsideButton: {
    width: 30,
    height: 30,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
    marginBottom: 0,
  },
  composerInput: {
    flex: 1,
    minHeight: 38,
    maxHeight: 132,
    backgroundColor: "transparent",
    borderRadius: 0,
    borderWidth: 0,
    paddingHorizontal: 0,
    paddingVertical: 7,
    color: colors.textPrimary,
    fontSize: 14,
  },
  composerInputDisabled: {
    color: colors.textSecondary,
  },
  sendButton: {
    width: 30,
    height: 30,
    borderRadius: radii.pill,
    backgroundColor: "#F47B20",
    alignItems: "center",
    justifyContent: "center",
  },
  sendButtonDisabled: {
    opacity: 0.55,
  },
} as const;
