import {
  colors,
  radii,
  shadows,
  spacing,
  typography,
} from "../../theme/tokens";
import { chatThreadMessageStyles } from "./chatThreadMessageStyles";
import { chatThreadSurfaceStyles } from "./chatThreadSurfaceStyles";

export const chatThreadStyles = {
  chatLayout: {
    flex: 1,
    minHeight: 0,
  },
  chatHeader: {
    paddingHorizontal: spacing.md,
    paddingTop: 8,
    paddingBottom: 6,
    gap: 8,
  },
  chatHeaderCompact: {
    paddingBottom: 2,
    gap: 6,
  },
  cleanHeaderTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  cleanHeaderSpacer: {
    flex: 1,
  },
  cleanNavButton: {
    width: 38,
    height: 38,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfacePanel,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    position: "relative",
  },
  cleanNavButtonCompact: {
    width: 34,
    height: 34,
  },
  cleanHeaderCopy: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 1,
    minHeight: 38,
  },
  cleanHeaderCopyCompact: {
    minHeight: 34,
  },
  chatHomeButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 0,
    minHeight: 28,
  },
  chatHomeButtonCompact: {
    gap: 0,
    minHeight: 28,
  },
  chatHomeIcon: {
    width: 22,
    height: 22,
    borderRadius: 7,
  },
  chatHomeIconCompact: {
    width: 20,
    height: 20,
    borderRadius: 6,
  },
  chatHomeToken: {
    width: 22,
    height: 22,
    borderRadius: 7,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.ink800,
  },
  chatHomeTokenCompact: {
    width: 20,
    height: 20,
    borderRadius: 6,
  },
  chatHomeTokenText: {
    color: colors.white,
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 0.4,
  },
  chatHomeTokenTextCompact: {
    fontSize: 8,
  },
  cleanHeaderEyebrow: {
    color: colors.textMuted,
    ...typography.eyebrow,
  },
  cleanHeaderTitle: {
    color: colors.textPrimary,
    fontSize: 17,
    lineHeight: 20,
    fontWeight: "800",
  },
  cleanHeaderTitleCompact: {
    fontSize: 16,
    lineHeight: 19,
  },
  cleanHeaderSubtitle: {
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 15,
    textAlign: "center",
    maxWidth: 236,
  },
  cleanHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  cleanNavBadge: {
    position: "absolute",
    top: -3,
    right: -2,
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    borderRadius: radii.pill,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  cleanNavBadgeText: {
    color: colors.white,
    fontSize: 10,
    fontWeight: "800",
  },
  cleanHeaderStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 0,
  },
  cleanReopenAction: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  cleanReopenActionText: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: "700",
  },
  composerMiniActions: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 2,
  },
  composerMiniAction: {
    width: 26,
    height: 26,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  cleanHeaderChipRail: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 6,
  },
  cleanHeaderChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    borderRadius: radii.pill,
    backgroundColor: colors.surfacePanelRaised,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
  },
  cleanHeaderChipAccent: {
    backgroundColor: colors.accentWash,
    borderColor: colors.accentMuted,
  },
  cleanHeaderChipText: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: "700",
    maxWidth: 220,
  },
  cleanHeaderChipTextAccent: {
    color: colors.accent,
  },
  chatHeaderTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  chatHeaderIdentity: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    flex: 1,
  },
  userBadge: {
    width: 46,
    height: 46,
    borderRadius: radii.pill,
    backgroundColor: "rgba(244,123,32,0.18)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  userBadgeText: {
    color: colors.accentSoft,
    fontSize: 18,
    fontWeight: "800",
  },
  chatHeaderCopy: {
    flex: 1,
    gap: 2,
  },
  chatEyebrow: {
    color: colors.accentSoft,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  chatTitle: {
    color: colors.white,
    fontSize: 24,
    fontWeight: "800",
  },
  chatSubtitle: {
    color: "rgba(238,243,247,0.74)",
    fontSize: 13,
  },
  chatHeaderActions: {
    alignItems: "flex-end",
    gap: spacing.sm,
  },
  chatHeaderActionRail: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderRadius: radii.pill,
    paddingHorizontal: 6,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  chatHeaderMetaRail: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  chatHeaderMetaChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  chatHeaderMetaText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: "700",
    maxWidth: 180,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  iconButtonBadge: {
    position: "absolute",
    top: -3,
    right: -3,
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    borderRadius: radii.pill,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  iconButtonBadgeText: {
    color: colors.white,
    fontSize: 10,
    fontWeight: "800",
  },
  chatPanel: {
    flex: 1,
    minHeight: 0,
    backgroundColor: "transparent",
    paddingTop: 6,
    paddingBottom: spacing.sm,
    paddingHorizontal: spacing.lg,
    gap: spacing.sm,
  },
  chatPanelKeyboardVisible: {
    paddingTop: 0,
    paddingBottom: spacing.xs,
    gap: spacing.sm,
  },
  threadHeaderCard: {
    backgroundColor: colors.surfacePanelRaised,
    borderRadius: 20,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    gap: 10,
  },
  threadHeaderChooserCard: {
    gap: spacing.xl,
    width: "100%",
    maxWidth: 560,
    alignSelf: "center",
    paddingHorizontal: 0,
    paddingVertical: 0,
    backgroundColor: "transparent",
    borderWidth: 0,
    borderColor: "transparent",
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0,
  },
  threadHeaderChooserCopy: {
    width: "100%",
    alignItems: "flex-start",
    alignSelf: "center",
    gap: spacing.xs,
  },
  threadHeaderFinalizationCard: {
    gap: spacing.md,
    paddingVertical: spacing.md,
    backgroundColor: colors.surfaceCanvas,
    borderColor: colors.surfaceStroke,
    ...shadows.soft,
  },
  threadHeaderTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: spacing.sm,
  },
  threadHeaderCopy: {
    flex: 1,
    gap: 2,
  },
  threadSpotlightBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
  },
  threadSpotlightBadgeCompact: {
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  threadSpotlightBadgeAccent: {
    backgroundColor: colors.accentWash,
    borderColor: colors.accentMuted,
  },
  threadSpotlightBadgeSuccess: {
    backgroundColor: colors.successWash,
    borderColor: colors.successSoft,
  },
  threadSpotlightBadgeDanger: {
    backgroundColor: colors.dangerWash,
    borderColor: colors.dangerSoft,
  },
  threadSpotlightText: {
    color: colors.textSecondary,
    fontSize: 10,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  threadSpotlightTextCompact: {
    maxWidth: 112,
  },
  threadSpotlightTextAccent: {
    color: colors.accent,
  },
  threadSpotlightTextSuccess: {
    color: colors.success,
  },
  threadSpotlightTextDanger: {
    color: colors.danger,
  },
  threadEyebrow: {
    color: colors.textMuted,
    ...typography.eyebrow,
  },
  threadTitle: {
    color: colors.textPrimary,
    fontSize: 17,
    lineHeight: 21,
    fontWeight: "800",
  },
  threadChooserTitle: {
    maxWidth: 320,
    fontSize: 20,
    lineHeight: 25,
    textAlign: "left",
  },
  threadDescription: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 16,
  },
  threadChooserDescription: {
    maxWidth: 300,
    fontSize: 14,
    lineHeight: 20,
    textAlign: "left",
  },
  threadCollapsedSummaryRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 8,
  },
  threadContextChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  threadContextChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceCanvas,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
  },
  threadContextChipCompact: {
    paddingHorizontal: 9,
    paddingVertical: 6,
  },
  threadContextChipAccent: {
    backgroundColor: colors.accentWash,
    borderColor: colors.accentMuted,
  },
  threadContextChipSuccess: {
    backgroundColor: colors.successWash,
    borderColor: colors.successSoft,
  },
  threadContextChipDanger: {
    backgroundColor: colors.dangerWash,
    borderColor: colors.dangerSoft,
  },
  threadContextChipText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
    maxWidth: 220,
  },
  threadContextChipTextCompact: {
    maxWidth: 132,
    fontSize: 11,
  },
  threadContextChipTextAccent: {
    color: colors.accent,
  },
  threadContextChipTextSuccess: {
    color: colors.success,
  },
  threadContextChipTextDanger: {
    color: colors.danger,
  },
  threadActionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  threadActionButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceCanvas,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
  },
  threadActionButtonCompact: {
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  threadActionButtonAccent: {
    backgroundColor: colors.accentWash,
    borderColor: colors.accentMuted,
  },
  threadActionButtonSuccess: {
    backgroundColor: colors.successWash,
    borderColor: colors.successSoft,
  },
  threadActionButtonDanger: {
    backgroundColor: colors.dangerWash,
    borderColor: colors.dangerSoft,
  },
  threadActionButtonText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "800",
  },
  threadActionButtonTextCompact: {
    maxWidth: 132,
    fontSize: 11,
  },
  threadActionButtonTextAccent: {
    color: colors.accent,
  },
  threadActionButtonTextSuccess: {
    color: colors.success,
  },
  threadActionButtonTextDanger: {
    color: colors.danger,
  },
  threadInsightGrid: {
    flexDirection: "column",
    gap: 8,
  },
  threadInsightCard: {
    width: "100%",
    minWidth: 0,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: 10,
    borderRadius: 16,
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  threadInsightCardAccent: {
    backgroundColor: colors.accentWash,
    borderColor: colors.accentMuted,
  },
  threadInsightCardSuccess: {
    backgroundColor: colors.successWash,
    borderColor: colors.successSoft,
  },
  threadInsightCardDanger: {
    backgroundColor: colors.dangerWash,
    borderColor: colors.dangerSoft,
  },
  threadInsightIcon: {
    width: 30,
    height: 30,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfacePanelRaised,
  },
  threadInsightIconAccent: {
    backgroundColor: colors.accentMuted,
  },
  threadInsightIconSuccess: {
    backgroundColor: "#DDF5E8",
  },
  threadInsightIconDanger: {
    backgroundColor: "#FCE1E1",
  },
  threadInsightCopy: {
    flex: 1,
    gap: 2,
  },
  threadInsightLabel: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  threadInsightValue: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: "800",
  },
  threadInsightDetail: {
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 16,
  },
  threadInsightSummaryRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  threadInsightSummaryChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 14,
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  threadInsightSummaryLabel: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  threadInsightSummaryValue: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: "800",
    maxWidth: 132,
  },
  threadToggleButton: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 2,
  },
  threadToggleButtonCompact: {
    paddingHorizontal: 2,
    paddingVertical: 6,
  },
  threadToggleButtonText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
  },
  threadChooserActionStack: {
    gap: 14,
    width: "100%",
    marginTop: spacing.md,
  },
  threadChooserActionCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.lg,
    minHeight: 86,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.surfacePanelRaised,
    ...shadows.soft,
  },
  threadChooserActionCardAccent: {
    backgroundColor: colors.surfacePanelRaised,
    borderColor: colors.accentMuted,
  },
  threadChooserActionCardSuccess: {
    backgroundColor: colors.surfacePanelRaised,
    borderColor: colors.successSoft,
  },
  threadChooserActionIcon: {
    width: 44,
    height: 44,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfacePanelRaised,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  threadChooserActionIconAccent: {
    backgroundColor: colors.accentMuted,
  },
  threadChooserActionIconSuccess: {
    backgroundColor: "#DDF5E8",
  },
  threadChooserActionCopy: {
    flex: 1,
    gap: 2,
  },
  threadChooserActionTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "800",
  },
  threadChooserActionDetail: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 18,
  },
  threadChooserTemplateSection: {
    gap: spacing.sm,
    paddingTop: spacing.xs,
    width: "100%",
  },
  threadChooserTemplateLabel: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.4,
    textAlign: "center",
    textTransform: "uppercase",
  },
  threadChooserTemplateGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  threadChooserTemplateButton: {
    width: "48%",
    flexGrow: 1,
    flexBasis: "48%",
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.surfacePanelRaised,
    ...shadows.soft,
  },
  threadChooserTemplateButtonText: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: "700",
  },
  threadFinalizationHero: {
    gap: spacing.md,
    padding: spacing.lg,
    borderRadius: 24,
    backgroundColor: colors.surfaceCanvas,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    ...shadows.soft,
  },
  threadFinalizationHeroAccent: {
    backgroundColor: colors.accentWash,
    borderColor: colors.accentMuted,
  },
  threadFinalizationHeroSuccess: {
    backgroundColor: colors.successWash,
    borderColor: colors.successSoft,
  },
  threadFinalizationHeroDanger: {
    backgroundColor: colors.dangerWash,
    borderColor: colors.dangerSoft,
  },
  threadFinalizationHeroTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  threadFinalizationTitle: {
    color: colors.textPrimary,
    fontSize: 21,
    lineHeight: 26,
    fontWeight: "800",
  },
  threadFinalizationDescription: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  threadFinalizationSection: {
    gap: spacing.sm,
  },
  threadFinalizationSectionLabel: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  threadTabs: {
    flexDirection: "row",
    gap: spacing.xs,
  },
  threadTabsCompact: {
    gap: 6,
  },
  cleanTabShell: {
    borderRadius: 16,
    backgroundColor: "transparent",
    padding: 0,
  },
  cleanTabShellCompact: {
    padding: 0,
  },
  threadTabsShell: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radii.md,
    padding: 6,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
  },
  threadTab: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
    backgroundColor: "transparent",
    borderRadius: 14,
    paddingVertical: 9,
    paddingHorizontal: spacing.sm,
  },
  threadTabCompact: {
    paddingVertical: 8,
    paddingHorizontal: spacing.sm,
  },
  threadTabDisabled: {
    opacity: 0.48,
  },
  threadTabActive: {
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  threadTabText: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: "700",
  },
  threadTabTextCompact: {
    fontSize: 13,
  },
  threadTabTextDisabled: {
    color: colors.textSecondary,
  },
  threadTabTextActive: {
    color: colors.textPrimary,
  },
  threadTabBadge: {
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    borderRadius: radii.pill,
    backgroundColor: colors.accentWash,
    alignItems: "center",
    justifyContent: "center",
  },
  threadTabBadgeActive: {
    backgroundColor: colors.accentWash,
  },
  threadTabBadgeText: {
    color: colors.accent,
    fontSize: 10,
    fontWeight: "800",
  },
  threadTabBadgeTextActive: {
    color: colors.accent,
  },
  threadMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  threadMetaText: {
    color: colors.textSecondary,
    fontSize: 12,
    flex: 1,
  },
  laudosSection: {
    gap: spacing.sm,
  },
  laudosSectionCopy: {
    flex: 1,
    gap: 2,
  },
  laudosSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  laudosSectionEyebrow: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  laudosSectionTitle: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "800",
  },
  laudosRail: {
    gap: spacing.sm,
    paddingRight: spacing.sm,
  },
  laudoChip: {
    width: 196,
    backgroundColor: colors.surfacePanelRaised,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    padding: spacing.md,
    gap: spacing.xs,
    ...shadows.soft,
  },
  laudoChipTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  laudoChipEyebrow: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  laudoChipEyebrowActive: {
    color: colors.accentSoft,
  },
  laudoChipActive: {
    backgroundColor: colors.ink800,
    borderColor: colors.ink800,
  },
  laudoChipTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "800",
  },
  laudoChipTitleActive: {
    color: colors.white,
  },
  laudoChipPreview: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
    minHeight: 36,
  },
  laudoChipPreviewActive: {
    color: "rgba(255,255,255,0.82)",
  },
  laudoChipMeta: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "600",
  },
  laudoChipMetaActive: {
    color: "rgba(255,255,255,0.66)",
  },
  laudoChipStatus: {
    alignSelf: "flex-start",
    borderRadius: radii.pill,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    marginTop: spacing.xs,
  },
  laudoChipStatusText: {
    fontSize: 11,
    fontWeight: "700",
  },
  activityStrip: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    backgroundColor: colors.surfacePanelRaised,
    padding: spacing.md,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
    ...shadows.soft,
  },
  activityStripIcon: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    backgroundColor: "rgba(244,123,32,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  activityStripCopy: {
    flex: 1,
    gap: 2,
  },
  activityStripTitle: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "800",
  },
  activityStripBody: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  activityStripTime: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "700",
  },
  offlineReadBanner: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.accentMuted,
    backgroundColor: colors.accentWash,
    padding: spacing.md,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  offlineReadBannerIcon: {
    width: 36,
    height: 36,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
  },
  offlineReadBannerCopy: {
    flex: 1,
    gap: 2,
  },
  offlineReadBannerTitle: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "800",
  },
  offlineReadBannerText: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  offlineQueueCard: {
    gap: spacing.sm,
    backgroundColor: colors.surfaceCanvas,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.accentMuted,
    padding: spacing.md,
    ...shadows.soft,
  },
  offlineQueueHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  offlineQueueActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  offlineQueueCopy: {
    flex: 1,
    gap: 2,
  },
  offlineQueueTitle: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "800",
  },
  offlineQueueDescription: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  offlineQueueSummaryChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  offlineQueueSummaryChip: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    borderRadius: radii.pill,
    backgroundColor: colors.surfacePanelRaised,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  offlineQueueSummaryChipAccent: {
    backgroundColor: colors.accentWash,
    borderColor: colors.accentMuted,
  },
  offlineQueueSummaryChipDanger: {
    backgroundColor: colors.dangerWash,
    borderColor: colors.dangerSoft,
  },
  offlineQueueSummaryChipText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "800",
  },
  offlineQueueSummaryChipTextAccent: {
    color: colors.accent,
  },
  offlineQueueSummaryChipTextDanger: {
    color: colors.danger,
  },
  offlineQueueSyncButton: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfacePanelRaised,
    borderWidth: 1,
    borderColor: colors.accentMuted,
  },
  offlineQueueOpenButton: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfacePanelRaised,
    borderWidth: 1,
    borderColor: colors.accentMuted,
  },
  offlineQueueSyncButtonDisabled: {
    opacity: 0.55,
  },
  offlineQueueItems: {
    gap: spacing.xs,
  },
  offlineQueueItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    backgroundColor: colors.surfacePanelRaised,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    paddingHorizontal: spacing.sm,
    paddingVertical: 10,
  },
  offlineQueueItemContent: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  offlineQueueItemBadge: {
    width: 32,
    height: 32,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.accentWash,
  },
  offlineQueueItemCopy: {
    flex: 1,
    gap: 2,
  },
  offlineQueueItemTitle: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: "700",
  },
  offlineQueueItemText: {
    color: colors.textSecondary,
    fontSize: 12,
  },
  offlineQueueItemMeta: {
    color: colors.textSecondary,
    fontSize: 11,
  },
  offlineQueueItemRemove: {
    width: 28,
    height: 28,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
  },
  offlineQueueFooter: {
    color: colors.textSecondary,
    fontSize: 12,
  },
  offlineModalToolbar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    borderRadius: radii.md,
    backgroundColor: colors.surfaceCanvas,
    borderWidth: 1,
    borderColor: colors.accentMuted,
  },
  offlineModalToolbarText: {
    flex: 1,
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  offlineModalSyncButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: colors.surfacePanelRaised,
    borderWidth: 1,
    borderColor: colors.accentMuted,
  },
  offlineModalSyncButtonDisabled: {
    opacity: 0.55,
  },
  offlineModalSyncText: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: "700",
  },
  offlineModalSyncTextDisabled: {
    color: colors.textSecondary,
  },
  offlineModalFilters: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  offlineModalFilterChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: colors.surfacePanel,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  offlineModalFilterChipActive: {
    backgroundColor: colors.ink800,
    borderColor: colors.ink800,
  },
  offlineModalFilterText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
  },
  offlineModalFilterTextActive: {
    color: colors.white,
  },
  offlineModalFilterCount: {
    minWidth: 24,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
  },
  offlineModalFilterCountActive: {
    backgroundColor: "rgba(255,255,255,0.16)",
  },
  offlineModalFilterCountText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "800",
  },
  offlineModalFilterCountTextActive: {
    color: colors.white,
  },
  offlineModalItem: {
    gap: spacing.sm,
    padding: spacing.md,
    borderRadius: radii.lg,
    backgroundColor: colors.surfacePanel,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    ...shadows.soft,
  },
  offlineModalItemTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
  },
  offlineModalItemBadge: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.accentWash,
  },
  offlineModalItemCopy: {
    flex: 1,
    gap: 4,
  },
  offlineModalItemHeading: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  offlineModalItemTitle: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "800",
  },
  offlineModalItemTime: {
    color: colors.textSecondary,
    fontSize: 11,
  },
  offlineModalItemText: {
    color: colors.textPrimary,
    fontSize: 13,
    lineHeight: 19,
  },
  offlineModalItemHint: {
    color: colors.textSecondary,
    fontSize: 12,
  },
  offlineModalItemStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    flexWrap: "wrap",
  },
  offlineModalItemStatusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: radii.pill,
    backgroundColor: colors.accentWash,
  },
  offlineModalItemStatusBadgeError: {
    backgroundColor: colors.dangerWash,
  },
  offlineModalItemStatusBadgeText: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "800",
  },
  offlineModalItemStatusBadgeTextError: {
    color: colors.danger,
  },
  offlineModalItemStatusText: {
    flex: 1,
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 16,
  },
  offlineModalItemActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: spacing.xs,
    flexWrap: "wrap",
  },
  offlineModalActionGhost: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    borderRadius: radii.pill,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "#FFD6B2",
  },
  offlineModalActionGhostDisabled: {
    opacity: 0.55,
  },
  offlineModalActionGhostText: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: "700",
  },
  offlineModalActionGhostTextDisabled: {
    color: colors.textSecondary,
  },
  offlineModalActionPrimary: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    borderRadius: radii.pill,
    backgroundColor: colors.accent,
  },
  offlineModalActionPrimaryText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: "800",
  },
  offlineModalActionSecondary: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceSoft,
  },
  offlineModalActionSecondaryText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
  },
  laudoStatusBadge: {
    borderRadius: radii.pill,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
  },
  laudoStatusText: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  reopenButton: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    backgroundColor: "#FFF5ED",
    borderRadius: radii.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
  },
  reopenButtonText: {
    color: colors.accent,
    fontWeight: "700",
  },
  threadBody: {
    flex: 1,
    minHeight: 0,
    backgroundColor: colors.surfacePanel,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xs,
    ...shadows.soft,
  },
  threadBodyEntryChooser: {
    backgroundColor: "transparent",
    borderRadius: 0,
    borderWidth: 0,
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 0,
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0,
  },
  threadBodyKeyboardVisible: {
    paddingTop: spacing.sm,
  },
  ...chatThreadSurfaceStyles,
  ...chatThreadMessageStyles,
  composerCard: {
    backgroundColor: "transparent",
    borderRadius: 0,
    borderWidth: 0,
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 2,
    gap: 4,
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0,
  },
  composerCardKeyboardVisible: {
    paddingTop: 0,
    paddingBottom: spacing.xs,
    gap: 4,
  },
  composerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  composerHeaderCopy: {
    flex: 1,
    gap: 2,
  },
  composerEyebrow: {
    color: colors.textMuted,
    ...typography.eyebrow,
  },
  composerTitle: {
    color: colors.textPrimary,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "800",
  },
  composerSubtitle: {
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 16,
  },
  composerStatusBadge: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
  },
  composerStatusBadgeAccent: {
    backgroundColor: colors.accentWash,
    borderColor: colors.accentMuted,
  },
  composerStatusBadgeSuccess: {
    backgroundColor: colors.successWash,
    borderColor: colors.successSoft,
  },
  composerStatusBadgeText: {
    color: colors.textSecondary,
    fontSize: 10,
    fontWeight: "800",
  },
  composerStatusBadgeTextAccent: {
    color: colors.accent,
  },
  composerStatusBadgeTextSuccess: {
    color: colors.success,
  },
  composerHint: {
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 17,
    paddingHorizontal: 2,
  },
  composerToolsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
    flexWrap: "wrap",
  },
  composerToolsLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  composerToolsText: {
    color: colors.textSecondary,
    fontSize: 12,
    flex: 1,
    textAlign: "left",
    minWidth: 180,
  },
  attachButton: {
    width: 42,
    height: 42,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  attachButtonDisabled: {
    opacity: 0.45,
  },
  attachmentDraftCard: {
    backgroundColor: colors.surfaceCanvas,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    padding: spacing.md,
    ...shadows.soft,
  },
  attachmentDraftHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
  },
  attachmentDraftIcon: {
    width: 36,
    height: 36,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.accentWash,
  },
  attachmentDraftPreview: {
    width: 52,
    height: 52,
    borderRadius: radii.sm,
    backgroundColor: "#E8EDF2",
  },
  attachmentDraftCopy: {
    flex: 1,
    gap: 2,
  },
  attachmentDraftTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "700",
  },
  attachmentDraftDescription: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  attachmentDraftRemove: {
    width: 30,
    height: 30,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
  },
  composerReferenceCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    backgroundColor: colors.surfaceCanvas,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    ...shadows.soft,
  },
  composerReferenceCopy: {
    flex: 1,
    gap: 2,
  },
  composerReferenceTitle: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  composerReferenceText: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 17,
  },
  composerReferenceRemove: {
    width: 28,
    height: 28,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
  },
} as const;
