import {
  colors,
  radii,
  shadows,
  spacing,
  typography,
} from "../../theme/tokens";

export const historyStyles = {
  historyModalBackdrop: {
    flex: 1,
    backgroundColor: colors.overlaySoft,
    padding: spacing.md,
    justifyContent: "flex-end",
  },
  historyModalCard: {
    backgroundColor: colors.surfacePanel,
    borderRadius: radii.xl,
    padding: spacing.lg,
    gap: spacing.md,
    maxHeight: "82%",
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    ...shadows.floating,
  },
  historyModalHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  historyBrandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    marginBottom: 2,
  },
  historyBrandIcon: {
    width: 28,
    height: 28,
    borderRadius: 10,
  },
  historyBrandEyebrow: {
    color: colors.textMuted,
    ...typography.eyebrow,
  },
  historyModalCopy: {
    flex: 1,
    gap: 4,
  },
  historyModalTitle: {
    color: colors.textPrimary,
    fontSize: 24,
    fontWeight: "800",
  },
  historyModalSubtitle: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  historyModalClose: {
    width: 40,
    height: 40,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceCanvas,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
  },
  historySearchShell: {
    minHeight: 46,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.surfaceCanvas,
  },
  historySearchInput: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 14,
    paddingVertical: 10,
  },
  historySummaryCard: {
    gap: spacing.sm,
    padding: spacing.md,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.surfacePanelRaised,
  },
  historySummaryHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  historySummaryCopy: {
    flex: 1,
    gap: 2,
  },
  historySummaryEyebrow: {
    color: colors.accent,
    ...typography.eyebrow,
  },
  historySummaryTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "800",
  },
  historySummaryTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  historySummaryCountLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
  },
  historySummaryMetricGrid: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  historySummaryMetricCard: {
    flex: 1,
    minWidth: 0,
    gap: 2,
    paddingHorizontal: spacing.sm,
    paddingVertical: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.surfaceCanvas,
  },
  historySummaryMetricValue: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: "800",
  },
  historySummaryMetricLabel: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  historySummaryPills: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  historySummaryPill: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 7,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.surfaceCanvas,
  },
  historySummaryPillText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "700",
  },
  historySummaryText: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 17,
  },
  historyFilterRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 4,
    padding: 4,
    borderRadius: 18,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  historyFilterChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: spacing.sm,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: "transparent",
  },
  historyFilterChipActive: {
    backgroundColor: colors.surfacePanelRaised,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  historyFilterChipText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
  },
  historyFilterChipTextActive: {
    color: colors.textPrimary,
  },
  historyFilterCount: {
    minWidth: 24,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfacePanelRaised,
  },
  historyFilterCountActive: {
    backgroundColor: colors.accentWash,
  },
  historyFilterCountText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "800",
  },
  historyFilterCountTextActive: {
    color: colors.accent,
  },
  historySections: {
    gap: spacing.lg,
    paddingBottom: spacing.lg,
  },
  historySection: {
    gap: spacing.sm,
  },
  historySectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  historySectionTitle: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  historySectionCountBadge: {
    minWidth: 26,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
  },
  historySectionCountText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "800",
  },
  historySectionItems: {
    gap: 0,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.surfacePanelRaised,
    overflow: "hidden",
  },
  historyItemShell: {
    position: "relative",
    overflow: "hidden",
    borderRadius: 0,
  },
  historyItemDeleteRail: {
    ...shadows.soft,
    position: "absolute",
    inset: 0,
    borderRadius: 18,
    backgroundColor: colors.dangerWash,
    borderWidth: 1,
    borderColor: colors.dangerSoft,
    alignItems: "flex-start",
    justifyContent: "center",
    paddingHorizontal: spacing.md,
  },
  historyItemDeleteRailBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: colors.surfacePanelRaised,
    borderWidth: 1,
    borderColor: colors.dangerSoft,
  },
  historyItemDeleteRailText: {
    color: colors.danger,
    fontSize: 12,
    fontWeight: "800",
  },
  historyItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.surfaceStroke,
    backgroundColor: colors.surfacePanelRaised,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
  },
  historyItemPrimary: {
    width: "100%",
  },
  historyItemLast: {
    borderBottomWidth: 0,
  },
  historyItemActive: {
    backgroundColor: colors.surfaceCanvas,
  },
  historyItemLead: {
    flex: 1,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
  },
  historyItemAccentBar: {
    width: 4,
    alignSelf: "stretch",
    minHeight: 56,
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceStrokeStrong,
  },
  historyItemAccentBarAccent: {
    backgroundColor: colors.accent,
  },
  historyItemAccentBarSuccess: {
    backgroundColor: colors.success,
  },
  historyItemAccentBarDanger: {
    backgroundColor: colors.danger,
  },
  historyItemAccentBarActive: {
    backgroundColor: colors.ink900,
  },
  historyItemCopy: {
    flex: 1,
    gap: 3,
  },
  historyItemTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  historyItemTitle: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: "800",
  },
  historyItemTitleActive: {
    color: colors.textPrimary,
  },
  historyItemPreview: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  historyItemPreviewActive: {
    color: colors.textSecondary,
  },
  historyItemBadgeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
    marginTop: 2,
  },
  historyItemBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.surfaceSoft,
  },
  historyItemBadgeAccent: {
    backgroundColor: colors.accentWash,
    borderColor: colors.accentMuted,
  },
  historyItemBadgeSuccess: {
    backgroundColor: colors.successWash,
    borderColor: colors.successSoft,
  },
  historyItemBadgeDanger: {
    backgroundColor: colors.dangerWash,
    borderColor: colors.dangerSoft,
  },
  historyItemBadgeActive: {
    borderColor: colors.surfaceStrokeStrong,
    backgroundColor: colors.white,
  },
  historyItemBadgeMutedActive: {
    borderColor: colors.surfaceStrokeStrong,
    backgroundColor: colors.white,
  },
  historyItemBadgeText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "700",
  },
  historyItemBadgeTextAccent: {
    color: colors.accent,
  },
  historyItemBadgeTextSuccess: {
    color: colors.success,
  },
  historyItemBadgeTextDanger: {
    color: colors.danger,
  },
  historyItemBadgeTextActive: {
    color: colors.textPrimary,
  },
  historyItemDetailRail: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
    marginTop: 4,
  },
  historyItemDetailPill: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  historyItemDetailPillActive: {
    backgroundColor: colors.white,
    borderColor: colors.surfaceStrokeStrong,
  },
  historyItemDetailPillText: {
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "700",
    maxWidth: 220,
  },
  historyItemChevronBadge: {
    width: 30,
    height: 30,
    marginTop: 2,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  historyItemChevronBadgeActive: {
    backgroundColor: colors.white,
    borderColor: colors.surfaceStrokeStrong,
  },
  historyItemDetailPillTextActive: {
    color: colors.textPrimary,
  },
  historyEmptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: spacing.xxl,
  },
  historyEmptyBrand: {
    width: 56,
    height: 56,
    borderRadius: 18,
  },
  historyEmptyTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "800",
  },
  historyEmptyText: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    textAlign: "center",
  },
} as const;
