import {
  colors,
  componentSizes,
  radii,
  shadows,
  spacing,
  typography,
} from "../../theme/tokens";

export const loginStyles = {
  loginScrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.xxxl,
    paddingBottom: spacing.xl,
  },
  loginScrollContentKeyboardVisible: {
    justifyContent: "flex-start",
    paddingTop: spacing.xl,
    paddingBottom: spacing.xl,
  },
  loginScreen: {
    flex: 1,
    justifyContent: "center",
  },
  brandStageCompact: {
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
  },
  brandHaloCompact: {
    position: "absolute",
    top: -8,
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "rgba(244,123,32,0.05)",
  },
  brandMarkCompact: {
    width: 76,
    height: 76,
    borderRadius: 22,
    ...shadows.soft,
  },
  brandLabelCompact: {
    color: colors.ink600,
    fontSize: 13,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 2.2,
  },
  loginCard: {
    width: "100%",
    maxWidth: 420,
    alignSelf: "center",
    gap: spacing.xl,
  },
  loginHero: {
    alignItems: "center",
    gap: spacing.lg,
  },
  loginIdentityMark: {
    width: 54,
    height: 54,
    borderRadius: 16,
    backgroundColor: colors.ink900,
    alignItems: "center",
    justifyContent: "center",
    ...shadows.card,
  },
  loginIdentityCore: {
    width: 14,
    height: 14,
    borderRadius: radii.pill,
    backgroundColor: colors.white,
  },
  loginCardHeader: {
    alignItems: "center",
    gap: 10,
  },
  loginManagedAccessBadge: {
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: spacing.md,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: colors.surfacePanel,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  loginManagedAccessBadgeText: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: "800",
  },
  loginCardEyebrow: {
    color: colors.textMuted,
    ...typography.eyebrow,
    textAlign: "center",
  },
  loginCardTitle: {
    color: colors.textPrimary,
    fontSize: 40,
    lineHeight: 44,
    fontWeight: "800",
    textAlign: "center",
    letterSpacing: -1,
    maxWidth: 280,
  },
  loginCardSubtitle: {
    color: colors.textSecondary,
    fontSize: 15,
    lineHeight: 22,
    maxWidth: 320,
    textAlign: "center",
  },
  loginFields: {
    gap: spacing.md,
  },
  loginFieldBlock: {
    gap: 0,
  },
  loginFieldLabel: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: "700",
  },
  mobileField: {
    minHeight: componentSizes.controlLg,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.surfaceStrokeStrong,
    backgroundColor: "transparent",
  },
  mobileFieldInput: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 17,
    paddingVertical: 12,
    paddingHorizontal: 0,
  },
  mobileFieldAction: {
    width: 32,
    height: 32,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  loginForgotRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  loginMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: spacing.md,
  },
  loginAccessInlineText: {
    flex: 1,
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 18,
  },
  loginRememberRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  loginCheckbox: {
    width: 18,
    height: 18,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#CAD6E2",
    backgroundColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
  },
  loginCheckboxActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  loginRememberText: {
    color: colors.textSecondary,
    fontSize: 13,
  },
  loginForgotLink: {
    color: colors.accent,
    fontSize: 13,
    fontWeight: "700",
  },
  loginPrimaryButton: {
    minHeight: 54,
    borderRadius: 14,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
    ...shadows.soft,
  },
  loginPrimaryButtonText: {
    color: colors.white,
    fontSize: 17,
    fontWeight: "800",
  },
  loginAccessNote: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
    padding: spacing.md,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.surfaceCanvas,
  },
  loginAccessNoteIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfacePanelRaised,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  loginAccessNoteCopy: {
    flex: 1,
    gap: 4,
  },
  loginAccessNoteTitle: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "800",
  },
  loginAccessNoteText: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  loginDividerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  loginDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.surfaceStroke,
  },
  loginDividerText: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: "700",
  },
  loginSocialStack: {
    gap: spacing.xs,
  },
  loginSocialButton: {
    minHeight: 50,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.surfacePanelRaised,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
  },
  loginSocialIconShell: {
    width: 32,
    height: 32,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
  },
  loginSocialButtonText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "700",
  },
  loginFooterText: {
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 18,
    textAlign: "center",
  },
} as const;
