import {
  colors,
  radii,
  shadows,
  spacing,
  typography,
} from "../../theme/tokens";

export const settingsSecurityStyles = {
  settingsDrawerContent: {
    gap: spacing.lg,
    paddingBottom: spacing.xl,
  },
  settingsPrintOverview: {
    gap: spacing.md,
    paddingBottom: spacing.md,
  },
  settingsPrintProfileBlock: {
    alignItems: "center",
    gap: spacing.sm,
  },
  settingsPrintAvatarShell: {
    width: 86,
    height: 86,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  settingsPrintAvatarImage: {
    width: 86,
    height: 86,
    borderRadius: radii.pill,
    backgroundColor: colors.surface,
  },
  settingsPrintAvatarFallback: {
    width: 86,
    height: 86,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.ink800,
  },
  settingsPrintAvatarInitials: {
    color: colors.white,
    fontSize: 30,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  settingsPrintAvatarEditButton: {
    position: "absolute",
    right: 1,
    bottom: 1,
    width: 28,
    height: 28,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfacePanelRaised,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
  },
  settingsPrintAvatarEditButtonDark: {
    backgroundColor: "#1D2B3A",
    borderColor: "#32455D",
  },
  settingsPrintProfileName: {
    color: colors.textPrimary,
    fontSize: 24,
    fontWeight: "800",
  },
  settingsPrintProfileNameDark: {
    color: "#F0F4F8",
  },
  settingsPrintSectionBlock: {
    gap: spacing.sm,
  },
  settingsPrintSectionTitle: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: "800",
  },
  settingsPrintSectionTitleDark: {
    color: "#F0F4F8",
  },
  settingsPrintGroupCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.surfacePanelRaised,
    overflow: "hidden",
  },
  settingsPrintGroupCardDark: {
    borderColor: "#2A3A4E",
    backgroundColor: "#162433",
  },
  settingsPrintRow: {
    minHeight: 66,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.surfaceStroke,
  },
  settingsPrintRowDark: {
    borderBottomColor: "#2D4156",
  },
  settingsPrintRowLast: {
    borderBottomWidth: 0,
  },
  settingsPrintRowDanger: {
    backgroundColor: "#FFF8F7",
  },
  settingsPrintRowDangerDark: {
    backgroundColor: "#2A1F26",
  },
  settingsPrintRowIconShell: {
    width: 32,
    height: 32,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  settingsPrintRowIconShellDark: {
    backgroundColor: "#1D2B3A",
    borderColor: "#32455D",
  },
  settingsPrintRowIconShellDanger: {
    backgroundColor: "#FFF1F1",
    borderColor: "#F2D3D3",
  },
  settingsPrintRowIconShellDangerDark: {
    backgroundColor: "#3A2730",
    borderColor: "#5A3A46",
  },
  settingsPrintRowCopy: {
    flex: 1,
    gap: 2,
  },
  settingsPrintRowTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "700",
  },
  settingsPrintRowTitleDark: {
    color: "#F0F4F8",
  },
  settingsPrintRowTitleDanger: {
    color: colors.danger,
  },
  settingsPrintRowSubtitle: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 16,
  },
  settingsPrintRowSubtitleDark: {
    color: "#AFC0D2",
  },
  settingsSummaryCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.surfacePanelRaised,
    padding: spacing.lg,
    gap: spacing.md,
  },
  settingsSummaryCardDark: {
    borderColor: "#2A3A4E",
    backgroundColor: "#162433",
  },
  settingsSummaryTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    flexWrap: "wrap",
    gap: spacing.md,
  },
  settingsSummaryMark: {
    width: 54,
    height: 54,
    borderRadius: 18,
  },
  settingsSummaryCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  settingsSummaryEyebrow: {
    color: colors.textMuted,
    ...typography.eyebrow,
  },
  settingsSummaryEyebrowDark: {
    color: "#AFC0D2",
  },
  settingsSummaryName: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: "800",
  },
  settingsSummaryNameDark: {
    color: "#F0F4F8",
  },
  settingsSummaryMeta: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  settingsSummaryMetaDark: {
    color: "#AFC0D2",
  },
  settingsSummaryChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  settingsHeroSignalGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  settingsHeroSignalCard: {
    flexBasis: 120,
    flexGrow: 1,
    flexShrink: 1,
    gap: 3,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.surfaceCanvas,
  },
  settingsHeroSignalLabel: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  settingsHeroSignalValue: {
    color: colors.textPrimary,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "800",
  },
  settingsOverviewGrid: {
    gap: spacing.sm,
  },
  settingsOverviewCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.surfacePanelRaised,
    padding: spacing.md,
  },
  settingsOverviewCardDark: {
    borderColor: "#2A3A4E",
    backgroundColor: "#162433",
  },
  settingsOverviewCardAccent: {
    backgroundColor: colors.surfaceCanvas,
    borderColor: colors.surfaceStrokeStrong,
  },
  settingsOverviewCardAccentDark: {
    backgroundColor: "#1B2E42",
    borderColor: "#3A526C",
  },
  settingsOverviewCardSuccess: {
    backgroundColor: colors.successWash,
    borderColor: colors.successSoft,
  },
  settingsOverviewCardSuccessDark: {
    backgroundColor: "#173026",
    borderColor: "#315A49",
  },
  settingsOverviewCardDanger: {
    backgroundColor: colors.dangerWash,
    borderColor: colors.dangerSoft,
  },
  settingsOverviewCardDangerDark: {
    backgroundColor: "#342229",
    borderColor: "#6A454F",
  },
  settingsOverviewIcon: {
    width: 44,
    height: 44,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.surfaceSoft,
  },
  settingsOverviewIconDark: {
    backgroundColor: "#1D2B3A",
    borderColor: "#32455D",
  },
  settingsOverviewIconAccent: {
    backgroundColor: colors.surfaceSoft,
    borderColor: colors.surfaceStroke,
  },
  settingsOverviewIconAccentDark: {
    backgroundColor: "#233447",
    borderColor: "#3F5A74",
  },
  settingsOverviewIconSuccess: {
    backgroundColor: colors.successWash,
    borderColor: colors.successSoft,
  },
  settingsOverviewIconSuccessDark: {
    backgroundColor: "#1F3A2E",
    borderColor: "#355E4A",
  },
  settingsOverviewIconDanger: {
    backgroundColor: colors.dangerWash,
    borderColor: colors.dangerSoft,
  },
  settingsOverviewIconDangerDark: {
    backgroundColor: "#432D35",
    borderColor: "#6A454F",
  },
  settingsOverviewCopy: {
    flex: 1,
    gap: spacing.xs,
  },
  settingsOverviewHeading: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  settingsOverviewTitle: {
    flex: 1,
    minWidth: 0,
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: "800",
  },
  settingsOverviewTitleDark: {
    color: "#F0F4F8",
  },
  settingsOverviewDescription: {
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 16,
  },
  settingsOverviewDescriptionDark: {
    color: "#AFC0D2",
  },
  settingsSearchShell: {
    minHeight: 50,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    backgroundColor: colors.surfaceCanvas,
  },
  settingsSearchInput: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 15,
    paddingVertical: 11,
  },
  settingsSearchClearButton: {
    width: 28,
    height: 28,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceMuted,
  },
  settingsFilterRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  settingsFilterChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: colors.surfacePanel,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  settingsFilterChipActive: {
    backgroundColor: colors.ink800,
    borderColor: colors.ink800,
  },
  settingsFilterChipText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
  },
  settingsFilterChipTextActive: {
    color: colors.white,
  },
  settingsFilterCount: {
    minWidth: 24,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
  },
  settingsFilterCountActive: {
    backgroundColor: "rgba(255,255,255,0.16)",
  },
  settingsFilterCountText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "800",
  },
  settingsFilterCountTextActive: {
    color: colors.white,
  },
  settingsFilterSummary: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
    paddingHorizontal: 4,
  },
  settingsSheetContent: {
    gap: spacing.md,
    paddingBottom: spacing.lg,
  },
  settingsFlowStack: {
    gap: spacing.md,
  },
  settingsInlineHero: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    backgroundColor: colors.surfaceCanvas,
    padding: spacing.md,
    ...shadows.soft,
  },
  settingsInlineHeroMark: {
    width: 52,
    height: 52,
    borderRadius: 18,
  },
  settingsInlineHeroMarkPlaceholder: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  settingsInlineHeroCopy: {
    flex: 1,
    gap: 4,
  },
  settingsInlineHeroTitle: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: "800",
  },
  settingsInlineHeroText: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  settingsInfoCard: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.surfacePanelRaised,
    padding: spacing.md,
    gap: 6,
  },
  settingsInfoTitle: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "800",
  },
  settingsInfoValue: {
    color: colors.textPrimary,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
    flexShrink: 1,
  },
  settingsInfoText: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  settingsInfoSubtle: {
    color: colors.ink600,
    fontSize: 11,
    lineHeight: 16,
  },
  settingsInfoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  settingsInfoGridItem: {
    flexBasis: 160,
    flexGrow: 1,
    flexShrink: 1,
  },
  settingsMiniList: {
    gap: spacing.sm,
  },
  settingsMiniListItem: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.surfacePanelRaised,
    padding: spacing.md,
    gap: 4,
  },
  settingsMiniListItemPressable: {
    gap: spacing.sm,
  },
  settingsMiniListItemActive: {
    borderColor: colors.ink700,
    backgroundColor: colors.surfaceCanvas,
  },
  settingsMiniListItemHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  settingsMiniListSelectionBadge: {
    width: 22,
    height: 22,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.surfacePanelRaised,
  },
  settingsMiniListSelectionBadgeActive: {
    borderColor: colors.ink800,
    backgroundColor: colors.ink800,
  },
  settingsMiniListTitle: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "800",
  },
  settingsMiniListTitleActive: {
    color: colors.textPrimary,
  },
  settingsMiniListMeta: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  settingsHelpArticleHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  settingsHelpArticleCopy: {
    flex: 1,
    gap: 2,
  },
  settingsHelpArticleBody: {
    color: colors.textPrimary,
    fontSize: 12,
    lineHeight: 20,
    paddingTop: spacing.xs,
  },
  settingsSheetNotice: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.successSoft,
    backgroundColor: colors.successWash,
    padding: spacing.md,
  },
  settingsSheetNoticeText: {
    flex: 1,
    color: colors.success,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "700",
  },
  settingsSheetFooter: {
    flexDirection: "row",
    gap: spacing.sm,
    paddingTop: spacing.xs,
  },
  settingsSheetGhostButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.surfacePanelRaised,
    alignItems: "center",
    justifyContent: "center",
  },
  settingsSheetGhostButtonText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "800",
  },
  settingsSheetPrimaryButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 16,
    backgroundColor: colors.ink800,
    alignItems: "center",
    justifyContent: "center",
  },
  settingsSheetPrimaryButtonDisabled: {
    opacity: 0.55,
  },
  settingsSheetPrimaryButtonText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: "800",
  },
  confirmSheetCard: {
    backgroundColor: colors.surfacePanel,
    borderRadius: radii.xl,
    padding: spacing.lg,
    gap: spacing.md,
    maxHeight: "68%",
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    ...shadows.panel,
  },
  confirmSheetIcon: {
    width: 42,
    height: 42,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF1F1",
    borderWidth: 1,
    borderColor: "#F1CCCC",
  },
  confirmSheetTitle: {
    color: colors.textPrimary,
    fontSize: 22,
    fontWeight: "800",
  },
  confirmSheetText: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  confirmSheetHint: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  confirmSheetHintStrong: {
    color: colors.danger,
    fontWeight: "800",
  },
  confirmSheetDangerButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 16,
    backgroundColor: colors.danger,
    alignItems: "center",
    justifyContent: "center",
  },
  confirmSheetDangerButtonText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: "800",
  },
  settingsGroupLabel: {
    paddingHorizontal: 2,
  },
  settingsGroupEyebrow: {
    color: colors.textMuted,
    ...typography.eyebrow,
  },
  settingsGroupDescription: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  settingsSection: {
    gap: spacing.sm,
  },
  settingsSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  settingsSectionIcon: {
    width: 36,
    height: 36,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  settingsSectionCopy: {
    flex: 1,
  },
  settingsSectionTitle: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: "800",
  },
  settingsSectionSubtitle: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  settingsCard: {
    backgroundColor: colors.surfacePanelRaised,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    overflow: "hidden",
  },
  settingsRow: {
    minHeight: 64,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.surfaceStroke,
  },
  settingsRowDanger: {
    backgroundColor: "#FFF9F8",
  },
  settingsBlockRow: {
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.surfaceStroke,
  },
  settingsBlockHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  settingsRowIcon: {
    width: 32,
    height: 32,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  settingsRowIconDanger: {
    backgroundColor: colors.dangerWash,
    borderColor: colors.dangerSoft,
  },
  settingsRowCopy: {
    flex: 1,
  },
  settingsRowTitle: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "700",
  },
  settingsRowTitleDanger: {
    color: colors.danger,
  },
  settingsRowDescription: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 17,
  },
  settingsRowMeta: {
    alignItems: "flex-end",
    justifyContent: "center",
    gap: 4,
  },
  settingsRowValue: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "700",
    textAlign: "right",
    maxWidth: 96,
  },
  settingsSegmentedControl: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  settingsSegmentPill: {
    minHeight: 36,
    paddingHorizontal: 14,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfacePanel,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  settingsSegmentPillActive: {
    backgroundColor: colors.ink800,
    borderColor: colors.ink800,
  },
  settingsSegmentText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "capitalize",
  },
  settingsSegmentTextActive: {
    color: colors.textInverse,
  },
  settingsScaleValue: {
    color: colors.ink700,
    fontSize: 13,
    fontWeight: "800",
  },
  settingsScaleTrack: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  settingsScaleStep: {
    flex: 1,
    height: 16,
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceMuted,
    justifyContent: "center",
    alignItems: "center",
  },
  settingsScaleStepActive: {
    backgroundColor: colors.surfaceStrokeStrong,
  },
  settingsScaleDot: {
    width: 8,
    height: 8,
    borderRadius: radii.pill,
    backgroundColor: "#CEB8A1",
  },
  settingsScaleDotActive: {
    width: 10,
    height: 10,
    backgroundColor: colors.accentSoft,
  },
  settingsScaleLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  settingsScaleLabel: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "600",
  },
  settingsFieldBlock: {
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: "#F1E8DF",
  },
  settingsFieldBlockNoDivider: {
    gap: spacing.xs,
  },
  settingsFieldLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  settingsTextField: {
    minHeight: 48,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    backgroundColor: colors.surfaceCanvas,
    color: colors.textPrimary,
    paddingHorizontal: spacing.md,
    fontSize: 15,
  },
  settingsTextArea: {
    minHeight: 124,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    backgroundColor: colors.surfaceCanvas,
    color: colors.textPrimary,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    fontSize: 15,
    textAlignVertical: "top",
  },
  settingsStatusPill: {
    minHeight: 24,
    paddingHorizontal: 10,
    maxWidth: "100%",
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  settingsStatusPillSuccess: {
    backgroundColor: colors.successWash,
    borderColor: colors.successSoft,
  },
  settingsStatusPillDanger: {
    backgroundColor: colors.dangerWash,
    borderColor: colors.dangerSoft,
  },
  settingsStatusPillAccent: {
    backgroundColor: colors.surfaceCanvas,
    borderColor: colors.surfaceStrokeStrong,
  },
  settingsStatusPillText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "700",
    flexShrink: 1,
  },
  settingsStatusPillTextSuccess: {
    color: colors.success,
  },
  settingsStatusPillTextDanger: {
    color: colors.danger,
  },
  settingsStatusPillTextAccent: {
    color: colors.ink700,
  },
  securityStack: {
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: "#F1E8DF",
  },
  securityIntroCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    backgroundColor: colors.surfaceCanvas,
    padding: spacing.md,
    gap: 6,
  },
  securityIntroTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "800",
  },
  securityIntroText: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  securityRecoveryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
    paddingTop: spacing.xs,
  },
  securityRecoveryCode: {
    minWidth: 108,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.surfacePanelRaised,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  securityRecoveryCodeText: {
    color: colors.textPrimary,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.6,
  },
  securityProviderCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    backgroundColor: colors.surfacePanel,
    padding: spacing.md,
    gap: spacing.sm,
  },
  securityProviderMain: {
    flexDirection: "row",
    gap: spacing.sm,
    alignItems: "center",
  },
  securityProviderIconShell: {
    width: 42,
    height: 42,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  securityProviderCopy: {
    flex: 1,
    gap: 4,
  },
  securityProviderHeading: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  securityProviderTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "800",
  },
  securityProviderMeta: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  securityProviderActionButton: {
    alignSelf: "flex-start",
    minHeight: 34,
    paddingHorizontal: 14,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.ink800,
  },
  securityProviderActionButtonDanger: {
    backgroundColor: colors.dangerWash,
    borderWidth: 1,
    borderColor: colors.dangerSoft,
  },
  securityProviderActionText: {
    color: colors.textInverse,
    fontSize: 12,
    fontWeight: "800",
  },
  securityProviderActionTextDanger: {
    color: colors.danger,
  },
  securitySessionCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    backgroundColor: colors.surfacePanel,
    padding: spacing.md,
    gap: spacing.sm,
  },
  securitySessionTop: {
    gap: spacing.xs,
  },
  securitySessionCopy: {
    gap: 4,
  },
  securitySessionHeading: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  securitySessionTitle: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "800",
  },
  securitySessionMeta: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  securitySessionActionButton: {
    alignSelf: "flex-start",
    minHeight: 34,
    paddingHorizontal: 14,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
  },
  securitySessionActionButtonDisabled: {
    backgroundColor: colors.surfaceMuted,
  },
  securitySessionActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  securitySessionReviewButton: {
    backgroundColor: colors.surfaceSoft,
    borderColor: colors.surfaceStroke,
  },
  securitySessionReviewButtonDanger: {
    backgroundColor: colors.dangerWash,
    borderColor: colors.dangerSoft,
  },
  securitySessionActionText: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: "800",
  },
  securitySessionReviewButtonText: {
    color: colors.textPrimary,
  },
  securitySessionReviewButtonTextDanger: {
    color: colors.danger,
  },
  securityEventCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    backgroundColor: colors.surfacePanel,
    padding: spacing.md,
    gap: 6,
  },
  securityEventTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  securityEventTitle: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "800",
  },
  securityEventMeta: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  securityEventStatus: {
    color: colors.ink700,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  securityFootnote: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
} as const;
