import { buildInspectorRootSettingsDrawerProps } from "./buildInspectorRootSettingsDrawerProps";

describe("buildInspectorRootSettingsDrawerProps", () => {
  it("monta o settings drawer a partir do estado derivado compartilhado", () => {
    const props = buildInspectorRootSettingsDrawerProps({
      accountState: {
        email: "inspetor@tariel.test",
        emailAtualConta: "conta@tariel.test",
        handleAlterarEmail: jest.fn(),
        handleAlterarSenha: jest.fn(),
        handleEditarPerfil: jest.fn(),
        handleSolicitarLogout: jest.fn(),
        handleUploadFotoPerfil: jest.fn(),
        perfilFotoHint: "iniciais",
        perfilFotoUri: "https://tariel.test/avatar.png",
      },
      baseState: {
        artigosAjudaFiltrados: [
          { id: "1", categoria: "Conta", titulo: "Ajuda" },
        ],
        contaEmailLabel: "conta@tariel.test",
        contaTelefoneLabel: "(11) 99999-0000",
        conversasOcultasTotal: 1,
        conversasVisiveisTotal: 3,
        corDestaqueResumoConfiguracao: "Laranja",
        detalheGovernancaConfiguracao:
          "PDF oficial divergente em 1 caso disponível no mobile.",
        eventosSegurancaFiltrados: [],
        existeProvedorDisponivel: true,
        iniciaisPerfilConfiguracao: "GT",
        integracoesConectadasTotal: 1,
        integracoesDisponiveisTotal: 2,
        mostrarGrupoContaAcesso: true,
        mostrarGrupoExperiencia: true,
        mostrarGrupoSeguranca: true,
        mostrarGrupoSistema: true,
        nomeUsuarioExibicao: "Gabriel",
        outrasSessoesAtivas: false,
        perfilExibicaoLabel: "Gabriel",
        perfilNomeCompleto: "Gabriel Tariel",
        permissoesNegadasTotal: 0,
        planoResumoConfiguracao: "Plano Pro",
        previewPrivacidadeNotificacao: "Prévia completa",
        provedoresConectadosTotal: 1,
        provedorPrimario: "Email e senha",
        reemissoesRecomendadasTotal: 1,
        resumo2FAFootnote: "",
        resumo2FAStatus: "Desativado",
        resumoAlertaMetodosConta: "",
        resumoBlindagemSessoes: "Sessão protegida",
        resumoCodigosRecuperacao: "Não gerados",
        resumoContaAcesso: "Conta ativa",
        resumoDadosConversas: "3 conversas",
        resumoExcluirConta: "Exclusão protegida",
        resumoFilaOffline: "Sem pendências",
        resumoFilaSuporteLocal: "Sem tickets",
        resumoGovernancaConfiguracao: "1 caso com reemissão recomendada",
        resumoMetodosConta: "Email e senha",
        resumoPermissoes: "Tudo liberado",
        resumoPermissoesCriticas: "Tudo liberado",
        resumoPrivacidadeNotificacoes: "Completo",
        resumoSessaoAtual: "Dispositivo atual",
        resumoSuporteApp: "Sem pendências",
        settingsDrawerInOverview: true,
        settingsDrawerMatchesPage: true,
        settingsDrawerMatchesSection: false,
        settingsDrawerPageSections: [],
        settingsDrawerSectionMenuAtiva: false,
        settingsDrawerSubtitle: "Resumo",
        settingsDrawerTitle: "Configurações",
        settingsPrintDarkMode: false,
        sessoesSuspeitasTotal: 0,
        temaResumoConfiguracao: "Claro",
        temPrioridadesConfiguracao: false,
        ticketsBugTotal: 0,
        ticketsFeedbackTotal: 0,
        totalSecoesConfiguracaoVisiveis: 4,
        ultimaVerificacaoAtualizacaoLabel: "Hoje",
        ultimoEventoProvedor: "",
        ultimoEventoSessao: "",
        ultimoTicketSuporteResumo: "Nenhum",
        workspaceResumoConfiguracao: "Tariel",
      } as never,
      experienceState: {
        aprendizadoIa: true,
        animacoesAtivas: true,
        chatCategoryEnabled: true,
        corDestaque: "laranja",
        criticalAlertsEnabled: true,
        densidadeInterface: "confortável",
        emailsAtivos: true,
        entradaPorVoz: true,
        estiloResposta: "objetivo",
        handleAbrirAjudaDitado: jest.fn(),
        handleAbrirModeloIa: jest.fn(),
        handleToggleEntradaPorVoz: jest.fn(),
        handleToggleNotificaPush: jest.fn(),
        handleToggleRespostaPorVoz: jest.fn(),
        handleToggleSpeechEnabled: jest.fn(),
        handleToggleVibracao: jest.fn(),
        idiomaResposta: "pt-BR",
        mediaCompression: "balanced",
        memoriaIa: true,
        mesaCategoryEnabled: true,
        mostrarCategoriaMesa: true,
        microfonePermitido: true,
        modeloIa: "gpt",
        nomeAutomaticoConversas: true,
        notificaPush: true,
        notificaRespostas: true,
        notificacoesPermitidas: true,
        onAbrirPermissaoNotificacoes: jest.fn(),
        onCyclePreferredVoice: jest.fn(),
        preferredVoiceLabel: "Sistema",
        respostaPorVoz: false,
        setAnimacoesAtivas: jest.fn(),
        setAprendizadoIa: jest.fn(),
        setChatCategoryEnabled: jest.fn(),
        setCorDestaque: jest.fn(),
        setCriticalAlertsEnabled: jest.fn(),
        setDensidadeInterface: jest.fn(),
        setEmailsAtivos: jest.fn(),
        setEstiloResposta: jest.fn(),
        setIdiomaResposta: jest.fn(),
        setMemoriaIa: jest.fn(),
        setMesaCategoryEnabled: jest.fn(),
        setNotificaRespostas: jest.fn(),
        setSomNotificacao: jest.fn(),
        setSpeechEnabled: jest.fn(),
        setSpeechRate: jest.fn(),
        setSystemCategoryEnabled: jest.fn(),
        setTamanhoFonte: jest.fn(),
        setTemperaturaIa: jest.fn(),
        setTemaApp: jest.fn(),
        setTomConversa: jest.fn(),
        setVoiceLanguage: jest.fn(),
        somNotificacao: "sino",
        speechEnabled: true,
        speechRate: 1,
        sttSupported: true,
        systemCategoryEnabled: true,
        tamanhoFonte: "médio",
        temperaturaIa: 0.4,
        temaApp: "claro",
        tomConversa: "formal",
        ttsSupported: true,
        vibracaoAtiva: true,
        voiceLanguage: "pt-BR",
      } as never,
      navigationState: {
        appBuildChannel: "preview",
        appVersionLabel: "1.0.0",
        configuracoesDrawerX: {} as never,
        fecharConfiguracoes: jest.fn(),
        handleAbrirPaginaConfiguracoes: jest.fn(),
        handleAbrirSecaoConfiguracoes: jest.fn(),
        handleVoltarResumoConfiguracoes: jest.fn(),
        onAbrirFilaOffline: jest.fn(),
        settingsDrawerPage: "overview",
        settingsDrawerPanResponder: { panHandlers: {} } as never,
      } as never,
      securityState: {
        analyticsOptIn: true,
        arquivosPermitidos: true,
        autoUploadAttachments: true,
        backupAutomatico: true,
        biometriaPermitida: true,
        cameraPermitida: true,
        codigo2FA: "",
        codigosRecuperacao: [],
        compartilharMelhoriaIa: true,
        crashReportsOptIn: true,
        deviceBiometricsEnabled: true,
        filtroEventosSeguranca: "todos",
        fixarConversas: true,
        handleApagarHistoricoConfiguracoes: jest.fn(),
        handleCompartilharCodigosRecuperacao: jest.fn(),
        handleConfirmarCodigo2FA: jest.fn(),
        handleDetalhesSegurancaArquivos: jest.fn(),
        handleEncerrarOutrasSessoes: jest.fn(),
        handleEncerrarSessao: jest.fn(),
        handleEncerrarSessaoAtual: jest.fn(),
        handleEncerrarSessoesSuspeitas: jest.fn(),
        handleExcluirConta: jest.fn(),
        handleExportarAntesDeExcluirConta: jest.fn(),
        handleExportarDados: jest.fn(),
        handleGerarCodigosRecuperacao: jest.fn(),
        handleGerenciarConversasIndividuais: jest.fn(),
        handleGerenciarPermissao: jest.fn(),
        handleLimparCache: jest.fn(),
        handleLimparTodasConversasConfig: jest.fn(),
        handleMudarMetodo2FA: jest.fn(),
        handleReautenticacaoSensivel: jest.fn(),
        handleReportarAtividadeSuspeita: jest.fn(),
        handleRevisarPermissoesCriticas: jest.fn(),
        handleRevisarSessao: jest.fn(),
        handleToggle2FA: jest.fn(),
        handleToggleBackupAutomatico: jest.fn(),
        handleToggleBiometriaNoDispositivo: jest.fn(),
        handleToggleMostrarConteudoNotificacao: jest.fn(),
        handleToggleMostrarSomenteNovaMensagem: jest.fn(),
        handleToggleOcultarConteudoBloqueado: jest.fn(),
        handleToggleProviderConnection: jest.fn(),
        handleToggleSincronizacaoDispositivos: jest.fn(),
        hideInMultitask: true,
        limpandoCache: false,
        lockTimeout: "5min",
        mediaCompression: "balanced",
        mostrarConteudoNotificacao: true,
        mostrarSomenteNovaMensagem: false,
        nomeAutomaticoConversas: true,
        ocultarConteudoBloqueado: false,
        provedoresConectados: [],
        reautenticacaoStatus: "Confirmada",
        recoveryCodesEnabled: false,
        requireAuthOnOpen: true,
        resumoCache: "Atualizado agora",
        retencaoDados: "90d",
        salvarHistoricoConversas: true,
        setAnalyticsOptIn: jest.fn(),
        setAutoUploadAttachments: jest.fn(),
        setCodigo2FA: jest.fn(),
        setCompartilharMelhoriaIa: jest.fn(),
        setCrashReportsOptIn: jest.fn(),
        setFiltroEventosSeguranca: jest.fn(),
        setFixarConversas: jest.fn(),
        setHideInMultitask: jest.fn(),
        setLockTimeout: jest.fn(),
        setMediaCompression: jest.fn(),
        setRecoveryCodesEnabled: jest.fn(),
        setRequireAuthOnOpen: jest.fn(),
        setRetencaoDados: jest.fn(),
        setSalvarHistoricoConversas: jest.fn(),
        setWifiOnlySync: jest.fn(),
        sessoesAtivas: [],
        sincronizacaoDispositivos: true,
        twoFactorEnabled: false,
        twoFactorMethod: "app",
        wifiOnlySync: false,
      } as never,
      supportAndSystemState: {
        economiaDados: "equilibrado",
        filaSuporteLocal: [],
        handleAbrirAjustesDoSistema: jest.fn(),
        handleAbrirCanalSuporte: jest.fn(),
        handleAbrirCentralAtividade: jest.fn(),
        handleAbrirSobreApp: jest.fn(),
        handleCentralAjuda: jest.fn(),
        handleEnviarFeedback: jest.fn(),
        handleExportarDiagnosticoApp: jest.fn(),
        handleLicencas: jest.fn(),
        handleLimparCache: jest.fn(),
        handleLimparFilaSuporteLocal: jest.fn(),
        handlePermissoes: jest.fn(),
        handlePoliticaPrivacidade: jest.fn(),
        handleRefresh: jest.fn(),
        handleReportarProblema: jest.fn(),
        handleTermosUso: jest.fn(),
        handleVerificarAtualizacoes: jest.fn(),
        idiomaApp: "pt-BR",
        regiaoApp: "BR",
        resumoCache: "Atualizado agora",
        resumoCentralAtividade: "Sem eventos",
        setEconomiaDados: jest.fn(),
        setIdiomaApp: jest.fn(),
        setRegiaoApp: jest.fn(),
        setUsoBateria: jest.fn(),
        sincronizandoDados: false,
        supportChannelLabel: "WhatsApp",
        usoBateria: "equilibrado",
        verificandoAtualizacoes: false,
      } as never,
    });

    expect(props.settingsDrawerTitle).toBe("Configurações");
    expect(props.overviewContentProps.nomeUsuarioExibicao).toBe("Gabriel");
    expect(props.overviewContentProps.reemissoesRecomendadasTotal).toBe(1);
    expect(props.overviewContentProps.resumoGovernancaConfiguracao).toBe(
      "1 caso com reemissão recomendada",
    );
    expect(props.supportSectionProps.artigosAjudaCount).toBe(1);
    expect(props.supportSectionProps.emailRetorno).toBe("conta@tariel.test");
    expect(props.experienceNotificationsSectionProps.showMesaCategory).toBe(
      true,
    );
    expect(props.systemSectionProps.appBuildChannel).toBe("preview");
  });
});
