from __future__ import annotations

from typing import Any


def _case(
    *,
    family_key: str,
    family_label: str,
    macro_categoria: str,
    expected_delivery_type: str,
    expected_execution_mode: str,
    object_title: str,
    location: str,
    reference: str,
    extra_fields: dict[str, Any],
    expected_doc_marker: str,
    expected_param_marker: str,
    attention: bool = True,
) -> dict[str, Any]:
    summary = f"{family_label} consolidado para validacao controlada da wave 3."
    attention_description = (
        f"Ajuste pendente relacionado a {family_label.lower()} antes do fechamento definitivo."
        if attention
        else "Sem nao conformidades relevantes para o fechamento desta entrega."
    )
    return {
        "family_key": family_key,
        "family_label": family_label,
        "macro_categoria": macro_categoria,
        "expected_delivery_type": expected_delivery_type,
        "expected_execution_mode": expected_execution_mode,
        "expected_status": "ajuste" if attention else "conforme",
        "expected_attention": attention,
        "expected_doc_marker": expected_doc_marker,
        "expected_param_marker": expected_param_marker,
        "object_title": object_title,
        "location": location,
        "reference": reference,
        "source_payload": {
            "objeto_principal": object_title,
            "localizacao": location,
            "local_inspecao": location,
            "codigo_interno": family_key.upper()[:18],
            "referencia_principal": reference,
            "metodo_aplicado": f"Metodo estruturado Tariel para {family_label.lower()}.",
            "condicoes_observadas": summary,
            "observacoes": summary,
            "descricao_pontos_atencao": attention_description,
            **extra_fields,
        },
        "first_message": f"Registro inicial de {family_label.lower()} em {location}.",
        "parecer_ia": summary,
        "diagnostico": summary,
        "attention_description": attention_description,
    }


WAVE_3_CASES: tuple[dict[str, Any], ...] = (
    _case(
        family_key="nr01_gro_pgr",
        family_label="NR01 · GRO PGR",
        macro_categoria="NR1",
        expected_delivery_type="pacote_documental",
        expected_execution_mode="analise_documental",
        object_title="Programa GRO/PGR da unidade matriz",
        location="Unidade Matriz - area administrativa",
        reference="DOC_0101 - gro_pgr_matriz_rev03.pdf",
        extra_fields={
            "inventario_riscos": "INV_0102 - inventario_riscos_matriz.xlsx",
            "plano_acao": "DOC_0103 - plano_acao_gro.pdf",
        },
        expected_doc_marker="Inventario:",
        expected_param_marker="Inventario riscos:",
    ),
    _case(
        family_key="nr01_ordem_servico_sst",
        family_label="NR01 · Ordem de servico SST",
        macro_categoria="NR1",
        expected_delivery_type="pacote_documental",
        expected_execution_mode="analise_documental",
        object_title="Ordem de servico SST da operacao industrial",
        location="Unidade Matriz - operacao industrial",
        reference="DOC_0104 - ordem_servico_sst_rev02.pdf",
        extra_fields={
            "ordem_servico": "DOC_0104 - ordem_servico_sst_rev02.pdf",
            "treinamento_obrigatorio": "Integracao SST e reciclagem anual",
            "funcoes_cobertas": "Operadores, manutencao e utilidades",
        },
        expected_doc_marker="Ordem servico:",
        expected_param_marker="Funcoes:",
    ),
    _case(
        family_key="nr04_diagnostico_sesmt",
        family_label="NR04 · Diagnostico SESMT",
        macro_categoria="NR4",
        expected_delivery_type="pacote_documental",
        expected_execution_mode="analise_documental",
        object_title="Diagnostico SESMT da planta quimica",
        location="Planta Quimica - escritorio SSMA",
        reference="DOC_0401 - diagnostico_sesmt_planta_quimica.pdf",
        extra_fields={
            "dimensionamento_sesmt": "Quadro tecnico dimensionado para 420 colaboradores",
            "organograma_sesmt": "DOC_0402 - organograma_sesmt.pdf",
        },
        expected_doc_marker="Dimensionamento:",
        expected_param_marker="Dimensionamento:",
    ),
    _case(
        family_key="nr05_implantacao_cipa",
        family_label="NR05 · Implantacao CIPA",
        macro_categoria="NR5",
        expected_delivery_type="pacote_documental",
        expected_execution_mode="analise_documental",
        object_title="Implantacao da CIPA na unidade fabril leste",
        location="Unidade Fabril Leste - RH",
        reference="DOC_0501 - ata_eleicao_cipa.pdf",
        extra_fields={
            "ata_eleicao": "DOC_0501 - ata_eleicao_cipa.pdf",
            "treinamento_cipa": "Treinamento inicial concluido para titulares e suplentes",
            "mandato_cipa": "Mandato 2026-2027",
        },
        expected_doc_marker="Ata:",
        expected_param_marker="Mandato:",
    ),
    _case(
        family_key="nr05_auditoria_cipa",
        family_label="NR05 · Auditoria CIPA",
        macro_categoria="NR5",
        expected_delivery_type="pacote_documental",
        expected_execution_mode="analise_documental",
        object_title="Auditoria da CIPA na unidade fabril leste",
        location="Unidade Fabril Leste - RH",
        reference="DOC_0507 - atas_cipa_2026.zip",
        extra_fields={
            "atas_reunioes": "DOC_0507 - atas_cipa_2026.zip",
            "plano_acao": "Plano de acao com 6 itens e dois pendentes",
            "reunioes_realizadas": "Reunioes mensais realizadas de janeiro a abril",
        },
        expected_doc_marker="Atas:",
        expected_param_marker="Reunioes:",
    ),
    _case(
        family_key="nr06_gestao_epi",
        family_label="NR06 · Gestao de EPI",
        macro_categoria="NR6",
        expected_delivery_type="inspecao_tecnica",
        expected_execution_mode="in_loco",
        object_title="Gestao de EPI na area de utilidades",
        location="Area de Utilidades - almoxarifado de EPI",
        reference="DOC_0602 - fichas_entrega_epi.pdf",
        extra_fields={
            "fichas_entrega": "DOC_0602 - fichas_entrega_epi.pdf",
            "ca_epi": "CA 12345 / CA 77889",
            "registros_entrega_epi": "Entregas atualizadas no ultimo ciclo mensal",
        },
        expected_doc_marker="Fichas entrega:",
        expected_param_marker="CA:",
        attention=False,
    ),
    _case(
        family_key="nr07_pcmso",
        family_label="NR07 · PCMSO",
        macro_categoria="NR7",
        expected_delivery_type="pacote_documental",
        expected_execution_mode="analise_documental",
        object_title="PCMSO corporativo da unidade matriz",
        location="Unidade Matriz - saude ocupacional",
        reference="DOC_0701 - pcmso_2026_rev04.pdf",
        extra_fields={
            "pcmso": "DOC_0701 - pcmso_2026_rev04.pdf",
            "aso": "Controle de ASO com 98% de vigencia",
            "exames_ocupacionais": "Admissional, periodico e retorno ao trabalho",
        },
        expected_doc_marker="PCMSO:",
        expected_param_marker="ASO:",
    ),
    _case(
        family_key="nr08_inspecao_edificacao_industrial",
        family_label="NR08 · Edificacao industrial",
        macro_categoria="NR8",
        expected_delivery_type="inspecao_tecnica",
        expected_execution_mode="in_loco",
        object_title="Edificacao industrial do galpao 2",
        location="Galpao 2 - unidade metalmecanica",
        reference="DOC_0801 - laudo_estrutural_galpao2.pdf",
        extra_fields={
            "laudo_estrutural": "DOC_0801 - laudo_estrutural_galpao2.pdf",
            "estrutura_civil": "Pilares e vigas sem deformacoes relevantes",
            "cobertura": "Telhas com pontos localizados de manutencao preventiva",
        },
        expected_doc_marker="Laudo estrutural:",
        expected_param_marker="Estrutura:",
    ),
    _case(
        family_key="nr09_avaliacao_exposicoes_ocupacionais",
        family_label="NR09 · Exposicoes ocupacionais",
        macro_categoria="NR9",
        expected_delivery_type="pacote_documental",
        expected_execution_mode="analise_documental",
        object_title="Avaliacao de exposicoes do GHE 03",
        location="Planta Quimica - GHE 03",
        reference="DOC_0901 - relatorio_higienico_ghe03.pdf",
        extra_fields={
            "relatorio_higienico": "DOC_0901 - relatorio_higienico_ghe03.pdf",
            "agentes_avaliados": "Ruido e poeira respiravel",
            "dosimetria": "Mediacoes quantitativas realizadas em abril de 2026",
        },
        expected_doc_marker="Relatorio higienico:",
        expected_param_marker="Agentes:",
    ),
    _case(
        family_key="nr11_inspecao_movimentacao_armazenagem",
        family_label="NR11 · Movimentacao e armazenagem",
        macro_categoria="NR11",
        expected_delivery_type="inspecao_tecnica",
        expected_execution_mode="in_loco",
        object_title="Movimentacao e armazenagem no centro de distribuicao",
        location="Centro de Distribuicao - corredor A",
        reference="DOC_1101 - checklist_empilhadeiras_cd.pdf",
        extra_fields={
            "checklist_operacao": "DOC_1101 - checklist_empilhadeiras_cd.pdf",
            "empilhadeiras": "Empilhadeiras E-12 e E-15 em rotina",
            "sinalizacao": "Demarcacao de solo atualizada no corredor A",
        },
        expected_doc_marker="Checklist:",
        expected_param_marker="Empilhadeiras:",
    ),
    _case(
        family_key="nr11_inspecao_equipamento_icamento",
        family_label="NR11 · Equipamento de icamento",
        macro_categoria="NR11",
        expected_delivery_type="inspecao_tecnica",
        expected_execution_mode="in_loco",
        object_title="Equipamento de icamento GT-220",
        location="Patio de manutencao pesada",
        reference="DOC_1110 - plano_icamento_tq02.pdf",
        extra_fields={
            "plano_icamento": "DOC_1110 - plano_icamento_tq02.pdf",
            "guindaste": "Guindaste GT-220 com capacidade nominal 220 t",
            "acessorios_icamento": "Lingas e manilhas com rastreabilidade valida",
        },
        expected_doc_marker="Plano icamento:",
        expected_param_marker="Guindaste:",
    ),
    _case(
        family_key="nr14_inspecao_forno_industrial",
        family_label="NR14 · Forno industrial",
        macro_categoria="NR14",
        expected_delivery_type="inspecao_tecnica",
        expected_execution_mode="in_loco",
        object_title="Forno industrial A3 da linha termica",
        location="Linha Termica - forno A3",
        reference="DOC_1401 - procedimento_forno_a3.pdf",
        extra_fields={
            "procedimento_operacional": "DOC_1401 - procedimento_forno_a3.pdf",
            "temperatura_operacao": "860 C em regime estavel",
            "exaustao": "Exaustao principal operando com renovacao adequada",
        },
        expected_doc_marker="Procedimento:",
        expected_param_marker="Temperatura:",
    ),
    _case(
        family_key="nr15_laudo_insalubridade",
        family_label="NR15 · Laudo de insalubridade",
        macro_categoria="NR15",
        expected_delivery_type="pacote_documental",
        expected_execution_mode="analise_documental",
        object_title="Laudo de insalubridade do setor de pintura",
        location="Setor de Pintura - unidade metalmecanica",
        reference="DOC_1501 - laudo_insalubridade_setor_pintura.pdf",
        extra_fields={
            "laudo_insalubridade": "DOC_1501 - laudo_insalubridade_setor_pintura.pdf",
            "agentes_insalubres": "Solventes aromaticos e ruido",
            "enquadramento_normativo": "Anexo 11 e anexo 13 avaliados",
        },
        expected_doc_marker="Laudo:",
        expected_param_marker="Agentes:",
    ),
    _case(
        family_key="nr16_laudo_periculosidade",
        family_label="NR16 · Laudo de periculosidade",
        macro_categoria="NR16",
        expected_delivery_type="pacote_documental",
        expected_execution_mode="analise_documental",
        object_title="Laudo de periculosidade da tancagem",
        location="Parque de Tancagem - area classificada",
        reference="DOC_1601 - laudo_periculosidade_tancagem.pdf",
        extra_fields={
            "laudo_periculosidade": "DOC_1601 - laudo_periculosidade_tancagem.pdf",
            "fontes_risco": "Inflamaveis liquidos e eletricidade",
            "areas_classificadas": "Zona 1 e zona 2 mapeadas no parque",
        },
        expected_doc_marker="Laudo:",
        expected_param_marker="Fonte risco:",
    ),
    _case(
        family_key="nr17_analise_ergonomica_trabalho",
        family_label="NR17 · Analise ergonomica",
        macro_categoria="NR17",
        expected_delivery_type="pacote_documental",
        expected_execution_mode="analise_documental",
        object_title="Analise ergonomica da celula de embalagem",
        location="Celula de Embalagem - linha 2",
        reference="DOC_1701 - aet_celula_embalagem.pdf",
        extra_fields={
            "aet": "DOC_1701 - aet_celula_embalagem.pdf",
            "postos_avaliados": "Postos 03, 04 e 05",
            "organizacao_trabalho": "Ritmo elevado com pausas formais entre ciclos",
        },
        expected_doc_marker="AET:",
        expected_param_marker="Postos:",
    ),
    _case(
        family_key="nr17_checklist_ergonomia",
        family_label="NR17 · Checklist de ergonomia",
        macro_categoria="NR17",
        expected_delivery_type="pacote_documental",
        expected_execution_mode="analise_documental",
        object_title="Checklist de ergonomia da expedicao",
        location="Expedicao - doca 3",
        reference="DOC_1707 - checklist_ergonomia_expedicao.pdf",
        extra_fields={
            "checklist_ergonomia": "DOC_1707 - checklist_ergonomia_expedicao.pdf",
            "posto_trabalho": "Posto de expedicao na doca 3",
            "mobiliario": "Bancadas com altura fixa e apoio parcial para antebracos",
            "pausas": "Pausas programadas no intervalo de 90 minutos",
        },
        expected_doc_marker="Checklist:",
        expected_param_marker="Posto:",
    ),
    _case(
        family_key="nr19_inspecao_area_explosivos",
        family_label="NR19 · Area de explosivos",
        macro_categoria="NR19",
        expected_delivery_type="inspecao_tecnica",
        expected_execution_mode="in_loco",
        object_title="Area de explosivos do paiol principal",
        location="Paiol principal - patio remoto",
        reference="DOC_1901 - licenca_paiol.pdf",
        extra_fields={
            "licenca_explosivos": "DOC_1901 - licenca_paiol.pdf",
            "armazenamento_explosivos": "Paiol principal com segregacao por lote e classe",
            "controle_acesso": "Controle de acesso com registro manual e digital",
        },
        expected_doc_marker="Licenca:",
        expected_param_marker="Armazenamento:",
    ),
    _case(
        family_key="nr21_condicoes_trabalho_ceu_aberto",
        family_label="NR21 · Trabalho a ceu aberto",
        macro_categoria="NR21",
        expected_delivery_type="inspecao_tecnica",
        expected_execution_mode="in_loco",
        object_title="Condicoes de trabalho da frente leste",
        location="Frente Leste - patio de utilidades",
        reference="DOC_2101 - pgr_ceu_aberto_frente_leste.pdf",
        extra_fields={
            "pgr": "DOC_2101 - pgr_ceu_aberto_frente_leste.pdf",
            "abrigos": "Abrigos moveis a 150 m da frente de trabalho",
            "hidratacao": "Pontos de agua e reposicao de eletrólitos disponiveis",
        },
        expected_doc_marker="PGR:",
        expected_param_marker="Abrigos:",
    ),
    _case(
        family_key="nr23_inspecao_protecao_incendios",
        family_label="NR23 · Protecao contra incendios",
        macro_categoria="NR23",
        expected_delivery_type="inspecao_tecnica",
        expected_execution_mode="in_loco",
        object_title="Sistema de protecao contra incendios do galpao 4",
        location="Galpao 4 - expedição",
        reference="DOC_2301 - avcb_galpao4.pdf",
        extra_fields={
            "avcb": "DOC_2301 - avcb_galpao4.pdf",
            "extintores": "Extintores revisados e sinalizados",
            "hidrantes": "Rede de hidrantes com pressao dentro do padrao",
        },
        expected_doc_marker="AVCB:",
        expected_param_marker="Extintores:",
        attention=False,
    ),
    _case(
        family_key="nr24_condicoes_sanitarias_conforto",
        family_label="NR24 · Condicoes sanitarias e conforto",
        macro_categoria="NR24",
        expected_delivery_type="inspecao_tecnica",
        expected_execution_mode="in_loco",
        object_title="Condicoes sanitarias do turno A",
        location="Unidade Alimenticia - apoio operacional",
        reference="DOC_2401 - checklist_conforto_turno_a.pdf",
        extra_fields={
            "checklist_sanitario": "DOC_2401 - checklist_conforto_turno_a.pdf",
            "sanitarios": "Sanitarios higienizados e abastecidos",
            "vestiarios": "Vestiarios organizados com armarios identificados",
        },
        expected_doc_marker="Checklist:",
        expected_param_marker="Sanitarios:",
        attention=False,
    ),
    _case(
        family_key="nr25_gestao_residuos_industriais",
        family_label="NR25 · Gestao de residuos industriais",
        macro_categoria="NR25",
        expected_delivery_type="pacote_documental",
        expected_execution_mode="analise_documental",
        object_title="Gestao de residuos da planta quimica",
        location="Planta Quimica - meio ambiente",
        reference="DOC_2501 - pgrs_planta_quimica.pdf",
        extra_fields={
            "pgrs": "DOC_2501 - pgrs_planta_quimica.pdf",
            "inventario_residuos": "Classe I, IIA e IIB mapeadas",
            "destinacao_final": "Transportadores homologados e destinacao rastreada",
        },
        expected_doc_marker="PGRS:",
        expected_param_marker="Inventario:",
    ),
    _case(
        family_key="nr26_sinalizacao_seguranca",
        family_label="NR26 · Sinalizacao de seguranca",
        macro_categoria="NR26",
        expected_delivery_type="inspecao_tecnica",
        expected_execution_mode="in_loco",
        object_title="Sinalizacao de seguranca do centro de distribuicao",
        location="Centro de Distribuicao - corredores e rotas",
        reference="DOC_2601 - projeto_sinalizacao_cd.pdf",
        extra_fields={
            "projeto_sinalizacao": "DOC_2601 - projeto_sinalizacao_cd.pdf",
            "placas_sinalizacao": "Placas de rota, obrigacao e alerta atualizadas",
            "demarcacao_solo": "Demarcacao de solo renovada nos corredores A e B",
        },
        expected_doc_marker="Projeto:",
        expected_param_marker="Placas:",
        attention=False,
    ),
)

WAVE_3_FAMILIES: tuple[str, ...] = tuple(case["family_key"] for case in WAVE_3_CASES)
