# ==========================================
# TARIEL CONTROL TOWER — SECURITY_SUPPORT.PY
# Responsabilidade: Fachada compatível para portal, cache local e persistência de sessões
# ==========================================

from __future__ import annotations

from app.shared.security_portal_state import (
    CHAVE_EMPRESA_ID,
    CHAVE_NIVEL_ACESSO,
    CHAVE_NOME,
    CHAVE_SESSION_TOKEN,
    CHAVE_USUARIO_ID,
    PORTAL_ADMIN,
    PORTAL_CLIENTE,
    PORTAL_INSPETOR,
    PORTAL_REVISOR,
    _limpar_chaves_sessao_request,
    definir_sessao_portal,
    destino_http_portal,
    empresa_tem_escopo_plataforma,
    limpar_sessao_portal,
    nivel_acesso_sessao_portal,
    niveis_permitidos_portal,
    normalizar_portal_sessao,
    obter_dados_sessao_portal,
    obter_token_bearer_request,
    portal_por_caminho,
    usuario_admin_portal_autorizado,
    usuario_ocupa_slot_operacional,
    usuario_tem_acesso_portal,
    usuario_tem_bloqueio_ativo,
    usuario_tem_nivel,
    usuario_tem_niveis_permitidos,
    usuario_portal_switch_links,
    usuario_portais_habilitados,
    usuario_tem_escopo_plataforma,
)
from app.shared.security_session_store import (
    MetaSessao,
    SESSOES_ATIVAS,
    _CHANCE_LIMPEZA,
    _SESSAO_EXPIRACAO,
    _SESSAO_META,
    _contexto_sessao_confere,
    _limpar_sessoes_expiradas,
    _lock_sessoes,
    _normalizar_ip,
    _renovar_sessao_se_necessario,
    atualizar_meta_sessao,
    contar_sessoes_ativas,
    criar_sessao,
    encerrar_sessao,
    encerrar_todas_sessoes_usuario,
    obter_meta_sessao,
    token_esta_ativo,
)

__all__ = [
    "CHAVE_EMPRESA_ID",
    "CHAVE_NIVEL_ACESSO",
    "CHAVE_NOME",
    "CHAVE_SESSION_TOKEN",
    "CHAVE_USUARIO_ID",
    "MetaSessao",
    "PORTAL_ADMIN",
    "PORTAL_CLIENTE",
    "PORTAL_INSPETOR",
    "PORTAL_REVISOR",
    "SESSOES_ATIVAS",
    "_CHANCE_LIMPEZA",
    "_SESSAO_EXPIRACAO",
    "_SESSAO_META",
    "_contexto_sessao_confere",
    "_limpar_chaves_sessao_request",
    "_limpar_sessoes_expiradas",
    "_lock_sessoes",
    "_normalizar_ip",
    "_renovar_sessao_se_necessario",
    "atualizar_meta_sessao",
    "contar_sessoes_ativas",
    "criar_sessao",
    "definir_sessao_portal",
    "destino_http_portal",
    "encerrar_sessao",
    "encerrar_todas_sessoes_usuario",
    "empresa_tem_escopo_plataforma",
    "limpar_sessao_portal",
    "nivel_acesso_sessao_portal",
    "niveis_permitidos_portal",
    "normalizar_portal_sessao",
    "obter_dados_sessao_portal",
    "obter_meta_sessao",
    "obter_token_bearer_request",
    "portal_por_caminho",
    "token_esta_ativo",
    "usuario_admin_portal_autorizado",
    "usuario_ocupa_slot_operacional",
    "usuario_tem_acesso_portal",
    "usuario_tem_bloqueio_ativo",
    "usuario_tem_nivel",
    "usuario_tem_niveis_permitidos",
    "usuario_portal_switch_links",
    "usuario_portais_habilitados",
    "usuario_tem_escopo_plataforma",
]
