import { StyleSheet } from "react-native";

import { colors, radii, shadows, spacing } from "../../theme/tokens";

export const modalStyles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: colors.overlayStrong,
    justifyContent: "flex-end",
    padding: spacing.md,
  },
  card: {
    maxHeight: "88%",
    backgroundColor: colors.surfacePanel,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    padding: spacing.lg,
    gap: spacing.md,
    ...shadows.floating,
  },
  header: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  headerCopy: {
    flex: 1,
    gap: 4,
  },
  eyebrow: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.7,
    textTransform: "uppercase",
  },
  title: {
    color: colors.textPrimary,
    fontSize: 22,
    fontWeight: "800",
  },
  description: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  closeButton: {
    width: 34,
    height: 34,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceCanvas,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
  },
  loadingState: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingVertical: spacing.md,
  },
  loadingText: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: "600",
  },
  scrollContent: {
    gap: spacing.md,
    paddingBottom: spacing.sm,
  },
  summaryHero: {
    gap: spacing.sm,
    padding: spacing.md,
    borderRadius: radii.xl,
    borderWidth: 1,
  },
  summaryHeroSuccess: {
    backgroundColor: colors.successWash,
    borderColor: colors.successSoft,
  },
  summaryHeroAccent: {
    backgroundColor: colors.accentWash,
    borderColor: colors.accentMuted,
  },
  summaryHeroDanger: {
    backgroundColor: colors.dangerWash,
    borderColor: colors.dangerSoft,
  },
  summaryHeroTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
  },
  summaryHeroIcon: {
    width: 34,
    height: 34,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfacePanelRaised,
  },
  summaryHeroIconSuccess: {
    backgroundColor: "#DDF5E8",
  },
  summaryHeroIconAccent: {
    backgroundColor: colors.accentMuted,
  },
  summaryHeroIconDanger: {
    backgroundColor: "#FCE1E1",
  },
  summaryHeroCopy: {
    flex: 1,
    gap: 2,
  },
  summaryHeroLabel: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: "800",
  },
  summaryHeroDescription: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  summaryChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  summaryChip: {
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    backgroundColor: colors.surfacePanelRaised,
    paddingHorizontal: spacing.sm,
    paddingVertical: 7,
  },
  summaryChipText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "700",
  },
  metricRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  metricCard: {
    flexBasis: "48%",
    flexGrow: 1,
    minHeight: 74,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.surfaceCanvas,
    padding: spacing.md,
    justifyContent: "center",
    gap: 2,
  },
  metricValue: {
    color: colors.textPrimary,
    fontSize: 20,
    fontWeight: "800",
  },
  metricLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "600",
  },
  section: {
    gap: spacing.sm,
  },
  sectionTitle: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: "800",
  },
  sectionDescription: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  issueCard: {
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.surfaceStroke,
    backgroundColor: colors.surfacePanelRaised,
    padding: spacing.md,
    gap: 6,
  },
  issueHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  issueTitle: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "700",
  },
  issueBadge: {
    color: colors.danger,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  issueMeta: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "600",
  },
  issueText: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  guideItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
  },
  guideCopy: {
    flex: 1,
    gap: 2,
  },
  guideTitle: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "700",
  },
  guideDescription: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  caseLabelRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  caseLabelChip: {
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.accentMuted,
    backgroundColor: colors.accentWash,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
  },
  caseLabelText: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: "700",
  },
  responsibilityText: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  reasonInput: {
    minHeight: 104,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    backgroundColor: colors.surfaceCanvas,
    color: colors.textPrimary,
    fontSize: 14,
    lineHeight: 20,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    textAlignVertical: "top",
  },
  reasonHint: {
    color: colors.textMuted,
    fontSize: 11,
    lineHeight: 16,
  },
  offlineCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.accentMuted,
    backgroundColor: colors.accentWash,
    padding: spacing.md,
  },
  offlineText: {
    flex: 1,
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  emptyState: {
    paddingVertical: spacing.lg,
  },
  emptyText: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  footer: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  secondaryButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.surfaceStrokeStrong,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceCanvas,
  },
  secondaryButtonText: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "700",
  },
  primaryButton: {
    flex: 1.2,
    minHeight: 46,
    borderRadius: radii.lg,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.accent,
  },
  primaryButtonDisabled: {
    opacity: 0.48,
  },
  primaryButtonText: {
    color: colors.white,
    fontSize: 13,
    fontWeight: "800",
  },
});
